//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CircuitBreakerSpec) DeepCopyInto(out *CircuitBreakerSpec) {
	*out = *in
	if in.ErrorRateThreshold != nil {
		in, out := &in.ErrorRateThreshold, &out.ErrorRateThreshold
		*out = new(float64)
		**out = **in
	}
	if in.Window != nil {
		in, out := &in.Window, &out.Window
		*out = new(Duration)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CircuitBreakerSpec.
func (in *CircuitBreakerSpec) DeepCopy() *CircuitBreakerSpec {
	if in == nil {
		return nil
	}
	out := new(CircuitBreakerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceBlock) DeepCopyInto(out *ComplianceBlock) {
	*out = *in
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ReportTemplate != nil {
		in, out := &in.ReportTemplate, &out.ReportTemplate
		*out = new(ResourceRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceBlock.
func (in *ComplianceBlock) DeepCopy() *ComplianceBlock {
	if in == nil {
		return nil
	}
	out := new(ComplianceBlock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostBlock) DeepCopyInto(out *CostBlock) {
	*out = *in
	if in.Estimator != nil {
		in, out := &in.Estimator, &out.Estimator
		*out = new(CostEstimator)
		(*in).DeepCopyInto(*out)
	}
	if in.Budget != nil {
		in, out := &in.Budget, &out.Budget
		*out = new(CostBudget)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostBlock.
func (in *CostBlock) DeepCopy() *CostBlock {
	if in == nil {
		return nil
	}
	out := new(CostBlock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostBudget) DeepCopyInto(out *CostBudget) {
	*out = *in
	if in.TokensPerCall != nil {
		in, out := &in.TokensPerCall, &out.TokensPerCall
		*out = new(int64)
		**out = **in
	}
	if in.UsdPerCall != nil {
		in, out := &in.UsdPerCall, &out.UsdPerCall
		*out = new(MoneyAmount)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostBudget.
func (in *CostBudget) DeepCopy() *CostBudget {
	if in == nil {
		return nil
	}
	out := new(CostBudget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostEstimator) DeepCopyInto(out *CostEstimator) {
	*out = *in
	if in.HistoricalWindow != nil {
		in, out := &in.HistoricalWindow, &out.HistoricalWindow
		*out = new(Duration)
		**out = **in
	}
	if in.TokensPerCall != nil {
		in, out := &in.TokensPerCall, &out.TokensPerCall
		*out = new(CostPercentiles)
		(*in).DeepCopyInto(*out)
	}
	if in.UsdPerCall != nil {
		in, out := &in.UsdPerCall, &out.UsdPerCall
		*out = new(CostPercentiles)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostEstimator.
func (in *CostEstimator) DeepCopy() *CostEstimator {
	if in == nil {
		return nil
	}
	out := new(CostEstimator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostPercentiles) DeepCopyInto(out *CostPercentiles) {
	*out = *in
	if in.P50 != nil {
		in, out := &in.P50, &out.P50
		*out = new(MoneyAmount)
		**out = **in
	}
	if in.P95 != nil {
		in, out := &in.P95, &out.P95
		*out = new(MoneyAmount)
		**out = **in
	}
	if in.P99 != nil {
		in, out := &in.P99, &out.P99
		*out = new(MoneyAmount)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostPercentiles.
func (in *CostPercentiles) DeepCopy() *CostPercentiles {
	if in == nil {
		return nil
	}
	out := new(CostPercentiles)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataResidency) DeepCopyInto(out *DataResidency) {
	*out = *in
	if in.AllowedRegions != nil {
		in, out := &in.AllowedRegions, &out.AllowedRegions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataResidency.
func (in *DataResidency) DeepCopy() *DataResidency {
	if in == nil {
		return nil
	}
	out := new(DataResidency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FallbackSpec) DeepCopyInto(out *FallbackSpec) {
	*out = *in
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(ResourceRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FallbackSpec.
func (in *FallbackSpec) DeepCopy() *FallbackSpec {
	if in == nil {
		return nil
	}
	out := new(FallbackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GovernanceBlock) DeepCopyInto(out *GovernanceBlock) {
	*out = *in
	if in.Classification != nil {
		in, out := &in.Classification, &out.Classification
		*out = new(Classification)
		**out = **in
	}
	if in.DataResidency != nil {
		in, out := &in.DataResidency, &out.DataResidency
		*out = new(DataResidency)
		(*in).DeepCopyInto(*out)
	}
	if in.PII != nil {
		in, out := &in.PII, &out.PII
		*out = new(PIIPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Compliance != nil {
		in, out := &in.Compliance, &out.Compliance
		*out = new(ComplianceBlock)
		(*in).DeepCopyInto(*out)
	}
	if in.RetentionDays != nil {
		in, out := &in.RetentionDays, &out.RetentionDays
		*out = new(int32)
		**out = **in
	}
	if in.Holds != nil {
		in, out := &in.Holds, &out.Holds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GovernanceBlock.
func (in *GovernanceBlock) DeepCopy() *GovernanceBlock {
	if in == nil {
		return nil
	}
	out := new(GovernanceBlock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PIIPolicy) DeepCopyInto(out *PIIPolicy) {
	*out = *in
	if in.PatternsRef != nil {
		in, out := &in.PatternsRef, &out.PatternsRef
		*out = new(ResourceRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PIIPolicy.
func (in *PIIPolicy) DeepCopy() *PIIPolicy {
	if in == nil {
		return nil
	}
	out := new(PIIPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReliabilityBlock) DeepCopyInto(out *ReliabilityBlock) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(Duration)
		**out = **in
	}
	if in.Retries != nil {
		in, out := &in.Retries, &out.Retries
		*out = new(RetryPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Fallback != nil {
		in, out := &in.Fallback, &out.Fallback
		*out = make([]FallbackSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CircuitBreaker != nil {
		in, out := &in.CircuitBreaker, &out.CircuitBreaker
		*out = new(CircuitBreakerSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReliabilityBlock.
func (in *ReliabilityBlock) DeepCopy() *ReliabilityBlock {
	if in == nil {
		return nil
	}
	out := new(ReliabilityBlock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetryPolicy) DeepCopyInto(out *RetryPolicy) {
	*out = *in
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(int32)
		**out = **in
	}
	if in.RetryOn != nil {
		in, out := &in.RetryOn, &out.RetryOn
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetryPolicy.
func (in *RetryPolicy) DeepCopy() *RetryPolicy {
	if in == nil {
		return nil
	}
	out := new(RetryPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOBlock) DeepCopyInto(out *SLOBlock) {
	*out = *in
	if in.P95LatencyMs != nil {
		in, out := &in.P95LatencyMs, &out.P95LatencyMs
		*out = new(int32)
		**out = **in
	}
	if in.P99LatencyMs != nil {
		in, out := &in.P99LatencyMs, &out.P99LatencyMs
		*out = new(int32)
		**out = **in
	}
	if in.SuccessRate != nil {
		in, out := &in.SuccessRate, &out.SuccessRate
		*out = new(float64)
		**out = **in
	}
	if in.ErrorBudget != nil {
		in, out := &in.ErrorBudget, &out.ErrorBudget
		*out = new(Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOBlock.
func (in *SLOBlock) DeepCopy() *SLOBlock {
	if in == nil {
		return nil
	}
	out := new(SLOBlock)
	in.DeepCopyInto(out)
	return out
}
