//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	sharedv1alpha1 "github.com/ai-keeper/ai-keeper/api/shared/v1alpha1"
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Agent) DeepCopyInto(out *Agent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Agent.
func (in *Agent) DeepCopy() *Agent {
	if in == nil {
		return nil
	}
	out := new(Agent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Agent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentAudit) DeepCopyInto(out *AgentAudit) {
	*out = *in
	if in.Retention != nil {
		in, out := &in.Retention, &out.Retention
		*out = new(sharedv1alpha1.Duration)
		**out = **in
	}
	if in.RedactPII != nil {
		in, out := &in.RedactPII, &out.RedactPII
		*out = new(bool)
		**out = **in
	}
	if in.StoreRaw != nil {
		in, out := &in.StoreRaw, &out.StoreRaw
		*out = new(AgentAuditStoreRaw)
		**out = **in
	}
	if in.Forwarders != nil {
		in, out := &in.Forwarders, &out.Forwarders
		*out = make([]AgentAuditForwarder, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentAudit.
func (in *AgentAudit) DeepCopy() *AgentAudit {
	if in == nil {
		return nil
	}
	out := new(AgentAudit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentAuditForwarder) DeepCopyInto(out *AgentAuditForwarder) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentAuditForwarder.
func (in *AgentAuditForwarder) DeepCopy() *AgentAuditForwarder {
	if in == nil {
		return nil
	}
	out := new(AgentAuditForwarder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentAuditStoreRaw) DeepCopyInto(out *AgentAuditStoreRaw) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentAuditStoreRaw.
func (in *AgentAuditStoreRaw) DeepCopy() *AgentAuditStoreRaw {
	if in == nil {
		return nil
	}
	out := new(AgentAuditStoreRaw)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentAutoscale) DeepCopyInto(out *AgentAutoscale) {
	*out = *in
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(int32)
		**out = **in
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(int32)
		**out = **in
	}
	if in.TargetConcurrency != nil {
		in, out := &in.TargetConcurrency, &out.TargetConcurrency
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentAutoscale.
func (in *AgentAutoscale) DeepCopy() *AgentAutoscale {
	if in == nil {
		return nil
	}
	out := new(AgentAutoscale)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentBudget) DeepCopyInto(out *AgentBudget) {
	*out = *in
	if in.TokensPerSession != nil {
		in, out := &in.TokensPerSession, &out.TokensPerSession
		*out = new(int64)
		**out = **in
	}
	if in.UsdPerSession != nil {
		in, out := &in.UsdPerSession, &out.UsdPerSession
		*out = new(sharedv1alpha1.MoneyAmount)
		**out = **in
	}
	if in.TokensPerStep != nil {
		in, out := &in.TokensPerStep, &out.TokensPerStep
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentBudget.
func (in *AgentBudget) DeepCopy() *AgentBudget {
	if in == nil {
		return nil
	}
	out := new(AgentBudget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentChannel) DeepCopyInto(out *AgentChannel) {
	*out = *in
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(sharedv1alpha1.ResourceRef)
		**out = **in
	}
	if in.RateLimit != nil {
		in, out := &in.RateLimit, &out.RateLimit
		*out = new(AgentChannelRateLimit)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentChannel.
func (in *AgentChannel) DeepCopy() *AgentChannel {
	if in == nil {
		return nil
	}
	out := new(AgentChannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentChannelRateLimit) DeepCopyInto(out *AgentChannelRateLimit) {
	*out = *in
	if in.RequestsPerMinute != nil {
		in, out := &in.RequestsPerMinute, &out.RequestsPerMinute
		*out = new(int32)
		**out = **in
	}
	if in.ConcurrentSessions != nil {
		in, out := &in.ConcurrentSessions, &out.ConcurrentSessions
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentChannelRateLimit.
func (in *AgentChannelRateLimit) DeepCopy() *AgentChannelRateLimit {
	if in == nil {
		return nil
	}
	out := new(AgentChannelRateLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentDeployment) DeepCopyInto(out *AgentDeployment) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Autoscale != nil {
		in, out := &in.Autoscale, &out.Autoscale
		*out = new(AgentAutoscale)
		(*in).DeepCopyInto(*out)
	}
	if in.Placement != nil {
		in, out := &in.Placement, &out.Placement
		*out = new(AgentPlacement)
		(*in).DeepCopyInto(*out)
	}
	if in.Rollout != nil {
		in, out := &in.Rollout, &out.Rollout
		*out = new(AgentRollout)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentDeployment.
func (in *AgentDeployment) DeepCopy() *AgentDeployment {
	if in == nil {
		return nil
	}
	out := new(AgentDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentDeterminism) DeepCopyInto(out *AgentDeterminism) {
	*out = *in
	if in.Temperature != nil {
		in, out := &in.Temperature, &out.Temperature
		*out = new(float64)
		**out = **in
	}
	if in.TopP != nil {
		in, out := &in.TopP, &out.TopP
		*out = new(float64)
		**out = **in
	}
	if in.Seed != nil {
		in, out := &in.Seed, &out.Seed
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentDeterminism.
func (in *AgentDeterminism) DeepCopy() *AgentDeterminism {
	if in == nil {
		return nil
	}
	out := new(AgentDeterminism)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentIdentity) DeepCopyInto(out *AgentIdentity) {
	*out = *in
	if in.Representation != nil {
		in, out := &in.Representation, &out.Representation
		*out = new(AgentRepresentation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentIdentity.
func (in *AgentIdentity) DeepCopy() *AgentIdentity {
	if in == nil {
		return nil
	}
	out := new(AgentIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentList) DeepCopyInto(out *AgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Agent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentList.
func (in *AgentList) DeepCopy() *AgentList {
	if in == nil {
		return nil
	}
	out := new(AgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentMemory) DeepCopyInto(out *AgentMemory) {
	*out = *in
	if in.ShortTerm != nil {
		in, out := &in.ShortTerm, &out.ShortTerm
		*out = new(AgentMemoryShortTerm)
		(*in).DeepCopyInto(*out)
	}
	if in.LongTerm != nil {
		in, out := &in.LongTerm, &out.LongTerm
		*out = new(AgentMemoryLongTerm)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentMemory.
func (in *AgentMemory) DeepCopy() *AgentMemory {
	if in == nil {
		return nil
	}
	out := new(AgentMemory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentMemoryLongTerm) DeepCopyInto(out *AgentMemoryLongTerm) {
	*out = *in
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(sharedv1alpha1.ResourceRef)
		**out = **in
	}
	if in.Retention != nil {
		in, out := &in.Retention, &out.Retention
		*out = new(sharedv1alpha1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentMemoryLongTerm.
func (in *AgentMemoryLongTerm) DeepCopy() *AgentMemoryLongTerm {
	if in == nil {
		return nil
	}
	out := new(AgentMemoryLongTerm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentMemoryShortTerm) DeepCopyInto(out *AgentMemoryShortTerm) {
	*out = *in
	if in.Window != nil {
		in, out := &in.Window, &out.Window
		*out = new(int32)
		**out = **in
	}
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(sharedv1alpha1.Duration)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(sharedv1alpha1.ResourceRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentMemoryShortTerm.
func (in *AgentMemoryShortTerm) DeepCopy() *AgentMemoryShortTerm {
	if in == nil {
		return nil
	}
	out := new(AgentMemoryShortTerm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentMetrics) DeepCopyInto(out *AgentMetrics) {
	*out = *in
	if in.Today != nil {
		in, out := &in.Today, &out.Today
		*out = new(AgentTodayMetrics)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentMetrics.
func (in *AgentMetrics) DeepCopy() *AgentMetrics {
	if in == nil {
		return nil
	}
	out := new(AgentMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPlacement) DeepCopyInto(out *AgentPlacement) {
	*out = *in
	if in.Zones != nil {
		in, out := &in.Zones, &out.Zones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Compliance != nil {
		in, out := &in.Compliance, &out.Compliance
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AirGapped != nil {
		in, out := &in.AirGapped, &out.AirGapped
		*out = new(bool)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPlacement.
func (in *AgentPlacement) DeepCopy() *AgentPlacement {
	if in == nil {
		return nil
	}
	out := new(AgentPlacement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRepresentation) DeepCopyInto(out *AgentRepresentation) {
	*out = *in
	if in.RequireUserContext != nil {
		in, out := &in.RequireUserContext, &out.RequireUserContext
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRepresentation.
func (in *AgentRepresentation) DeepCopy() *AgentRepresentation {
	if in == nil {
		return nil
	}
	out := new(AgentRepresentation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRollout) DeepCopyInto(out *AgentRollout) {
	*out = *in
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AnalysisInterval != nil {
		in, out := &in.AnalysisInterval, &out.AnalysisInterval
		*out = new(sharedv1alpha1.Duration)
		**out = **in
	}
	if in.AnalysisRef != nil {
		in, out := &in.AnalysisRef, &out.AnalysisRef
		*out = new(sharedv1alpha1.ResourceRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRollout.
func (in *AgentRollout) DeepCopy() *AgentRollout {
	if in == nil {
		return nil
	}
	out := new(AgentRollout)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRolloutStatus) DeepCopyInto(out *AgentRolloutStatus) {
	*out = *in
	if in.CurrentStep != nil {
		in, out := &in.CurrentStep, &out.CurrentStep
		*out = new(int32)
		**out = **in
	}
	if in.TrafficWeight != nil {
		in, out := &in.TrafficWeight, &out.TrafficWeight
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRolloutStatus.
func (in *AgentRolloutStatus) DeepCopy() *AgentRolloutStatus {
	if in == nil {
		return nil
	}
	out := new(AgentRolloutStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRuntime) DeepCopyInto(out *AgentRuntime) {
	*out = *in
	if in.MaxSteps != nil {
		in, out := &in.MaxSteps, &out.MaxSteps
		*out = new(int32)
		**out = **in
	}
	if in.MaxToolCalls != nil {
		in, out := &in.MaxToolCalls, &out.MaxToolCalls
		*out = new(int32)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(sharedv1alpha1.Duration)
		**out = **in
	}
	if in.Parallelism != nil {
		in, out := &in.Parallelism, &out.Parallelism
		*out = new(int32)
		**out = **in
	}
	if in.Determinism != nil {
		in, out := &in.Determinism, &out.Determinism
		*out = new(AgentDeterminism)
		(*in).DeepCopyInto(*out)
	}
	if in.Sandbox != nil {
		in, out := &in.Sandbox, &out.Sandbox
		*out = new(AgentSandbox)
		(*in).DeepCopyInto(*out)
	}
	if in.Budget != nil {
		in, out := &in.Budget, &out.Budget
		*out = new(AgentBudget)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRuntime.
func (in *AgentRuntime) DeepCopy() *AgentRuntime {
	if in == nil {
		return nil
	}
	out := new(AgentRuntime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSandbox) DeepCopyInto(out *AgentSandbox) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EgressAllowList != nil {
		in, out := &in.EgressAllowList, &out.EgressAllowList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSandbox.
func (in *AgentSandbox) DeepCopy() *AgentSandbox {
	if in == nil {
		return nil
	}
	out := new(AgentSandbox)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSkillBinding) DeepCopyInto(out *AgentSkillBinding) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSkillBinding.
func (in *AgentSkillBinding) DeepCopy() *AgentSkillBinding {
	if in == nil {
		return nil
	}
	out := new(AgentSkillBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSpec) DeepCopyInto(out *AgentSpec) {
	*out = *in
	in.Identity.DeepCopyInto(&out.Identity)
	if in.Skills != nil {
		in, out := &in.Skills, &out.Skills
		*out = make([]AgentSkillBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(AgentMemory)
		(*in).DeepCopyInto(*out)
	}
	in.Runtime.DeepCopyInto(&out.Runtime)
	if in.Guardrails != nil {
		in, out := &in.Guardrails, &out.Guardrails
		*out = new(GuardrailsBlock)
		(*in).DeepCopyInto(*out)
	}
	if in.Audit != nil {
		in, out := &in.Audit, &out.Audit
		*out = new(AgentAudit)
		(*in).DeepCopyInto(*out)
	}
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(AgentDeployment)
		(*in).DeepCopyInto(*out)
	}
	if in.Channels != nil {
		in, out := &in.Channels, &out.Channels
		*out = make([]AgentChannel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSpec.
func (in *AgentSpec) DeepCopy() *AgentSpec {
	if in == nil {
		return nil
	}
	out := new(AgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentStatus) DeepCopyInto(out *AgentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AttachedSkills != nil {
		in, out := &in.AttachedSkills, &out.AttachedSkills
		*out = make([]sharedv1alpha1.ResourceRef, len(*in))
		copy(*out, *in)
	}
	if in.EffectivePolicies != nil {
		in, out := &in.EffectivePolicies, &out.EffectivePolicies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(AgentMetrics)
		(*in).DeepCopyInto(*out)
	}
	if in.RolloutStatus != nil {
		in, out := &in.RolloutStatus, &out.RolloutStatus
		*out = new(AgentRolloutStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentStatus.
func (in *AgentStatus) DeepCopy() *AgentStatus {
	if in == nil {
		return nil
	}
	out := new(AgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTodayMetrics) DeepCopyInto(out *AgentTodayMetrics) {
	*out = *in
	if in.CostUsd != nil {
		in, out := &in.CostUsd, &out.CostUsd
		*out = new(sharedv1alpha1.MoneyAmount)
		**out = **in
	}
	if in.P95LatencyMs != nil {
		in, out := &in.P95LatencyMs, &out.P95LatencyMs
		*out = new(int32)
		**out = **in
	}
	if in.ErrorRate != nil {
		in, out := &in.ErrorRate, &out.ErrorRate
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTodayMetrics.
func (in *AgentTodayMetrics) DeepCopy() *AgentTodayMetrics {
	if in == nil {
		return nil
	}
	out := new(AgentTodayMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuardrailBehavior) DeepCopyInto(out *GuardrailBehavior) {
	*out = *in
	if in.SystemPrompt != nil {
		in, out := &in.SystemPrompt, &out.SystemPrompt
		*out = new(sharedv1alpha1.ResourceRef)
		**out = **in
	}
	if in.BlockedTopics != nil {
		in, out := &in.BlockedTopics, &out.BlockedTopics
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedTopics != nil {
		in, out := &in.AllowedTopics, &out.AllowedTopics
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RequiredCitations != nil {
		in, out := &in.RequiredCitations, &out.RequiredCitations
		*out = new(bool)
		**out = **in
	}
	if in.LanguageLock != nil {
		in, out := &in.LanguageLock, &out.LanguageLock
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuardrailBehavior.
func (in *GuardrailBehavior) DeepCopy() *GuardrailBehavior {
	if in == nil {
		return nil
	}
	out := new(GuardrailBehavior)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuardrailRule) DeepCopyInto(out *GuardrailRule) {
	*out = *in
	if in.Threshold != nil {
		in, out := &in.Threshold, &out.Threshold
		*out = new(float64)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuardrailRule.
func (in *GuardrailRule) DeepCopy() *GuardrailRule {
	if in == nil {
		return nil
	}
	out := new(GuardrailRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuardrailsBlock) DeepCopyInto(out *GuardrailsBlock) {
	*out = *in
	if in.Input != nil {
		in, out := &in.Input, &out.Input
		*out = make([]GuardrailRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = make([]GuardrailRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Behavior != nil {
		in, out := &in.Behavior, &out.Behavior
		*out = new(GuardrailBehavior)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuardrailsBlock.
func (in *GuardrailsBlock) DeepCopy() *GuardrailsBlock {
	if in == nil {
		return nil
	}
	out := new(GuardrailsBlock)
	in.DeepCopyInto(out)
	return out
}
