//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	sharedv1alpha1 "github.com/ai-keeper/ai-keeper/api/shared/v1alpha1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelEndpoint) DeepCopyInto(out *ModelEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelEndpoint.
func (in *ModelEndpoint) DeepCopy() *ModelEndpoint {
	if in == nil {
		return nil
	}
	out := new(ModelEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelEndpointAuthentication) DeepCopyInto(out *ModelEndpointAuthentication) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(ModelEndpointSecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelEndpointAuthentication.
func (in *ModelEndpointAuthentication) DeepCopy() *ModelEndpointAuthentication {
	if in == nil {
		return nil
	}
	out := new(ModelEndpointAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelEndpointCost) DeepCopyInto(out *ModelEndpointCost) {
	*out = *in
	if in.InputUsdPerMTok != nil {
		in, out := &in.InputUsdPerMTok, &out.InputUsdPerMTok
		*out = new(sharedv1alpha1.MoneyAmount)
		**out = **in
	}
	if in.OutputUsdPerMTok != nil {
		in, out := &in.OutputUsdPerMTok, &out.OutputUsdPerMTok
		*out = new(sharedv1alpha1.MoneyAmount)
		**out = **in
	}
	if in.CachedInputUsdPerMTok != nil {
		in, out := &in.CachedInputUsdPerMTok, &out.CachedInputUsdPerMTok
		*out = new(sharedv1alpha1.MoneyAmount)
		**out = **in
	}
	if in.EmbeddingUsdPerMTok != nil {
		in, out := &in.EmbeddingUsdPerMTok, &out.EmbeddingUsdPerMTok
		*out = new(sharedv1alpha1.MoneyAmount)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelEndpointCost.
func (in *ModelEndpointCost) DeepCopy() *ModelEndpointCost {
	if in == nil {
		return nil
	}
	out := new(ModelEndpointCost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelEndpointDeployment) DeepCopyInto(out *ModelEndpointDeployment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelEndpointDeployment.
func (in *ModelEndpointDeployment) DeepCopy() *ModelEndpointDeployment {
	if in == nil {
		return nil
	}
	out := new(ModelEndpointDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelEndpointList) DeepCopyInto(out *ModelEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelEndpointList.
func (in *ModelEndpointList) DeepCopy() *ModelEndpointList {
	if in == nil {
		return nil
	}
	out := new(ModelEndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelEndpointPrivacy) DeepCopyInto(out *ModelEndpointPrivacy) {
	*out = *in
	if in.TrainOnInputs != nil {
		in, out := &in.TrainOnInputs, &out.TrainOnInputs
		*out = new(bool)
		**out = **in
	}
	if in.ZeroRetention != nil {
		in, out := &in.ZeroRetention, &out.ZeroRetention
		*out = new(bool)
		**out = **in
	}
	if in.DPASigned != nil {
		in, out := &in.DPASigned, &out.DPASigned
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelEndpointPrivacy.
func (in *ModelEndpointPrivacy) DeepCopy() *ModelEndpointPrivacy {
	if in == nil {
		return nil
	}
	out := new(ModelEndpointPrivacy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelEndpointQuota) DeepCopyInto(out *ModelEndpointQuota) {
	*out = *in
	if in.TPM != nil {
		in, out := &in.TPM, &out.TPM
		*out = new(int64)
		**out = **in
	}
	if in.RPM != nil {
		in, out := &in.RPM, &out.RPM
		*out = new(int64)
		**out = **in
	}
	if in.TPD != nil {
		in, out := &in.TPD, &out.TPD
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelEndpointQuota.
func (in *ModelEndpointQuota) DeepCopy() *ModelEndpointQuota {
	if in == nil {
		return nil
	}
	out := new(ModelEndpointQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelEndpointResidency) DeepCopyInto(out *ModelEndpointResidency) {
	*out = *in
	if in.Sovereign != nil {
		in, out := &in.Sovereign, &out.Sovereign
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelEndpointResidency.
func (in *ModelEndpointResidency) DeepCopy() *ModelEndpointResidency {
	if in == nil {
		return nil
	}
	out := new(ModelEndpointResidency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelEndpointSecretRef) DeepCopyInto(out *ModelEndpointSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelEndpointSecretRef.
func (in *ModelEndpointSecretRef) DeepCopy() *ModelEndpointSecretRef {
	if in == nil {
		return nil
	}
	out := new(ModelEndpointSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelEndpointSpec) DeepCopyInto(out *ModelEndpointSpec) {
	*out = *in
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = new(ModelEndpointAuthentication)
		(*in).DeepCopyInto(*out)
	}
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ContextWindow != nil {
		in, out := &in.ContextWindow, &out.ContextWindow
		*out = new(int32)
		**out = **in
	}
	if in.MaxOutputTokens != nil {
		in, out := &in.MaxOutputTokens, &out.MaxOutputTokens
		*out = new(int32)
		**out = **in
	}
	if in.Cost != nil {
		in, out := &in.Cost, &out.Cost
		*out = new(ModelEndpointCost)
		(*in).DeepCopyInto(*out)
	}
	if in.Compliance != nil {
		in, out := &in.Compliance, &out.Compliance
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DataResidency != nil {
		in, out := &in.DataResidency, &out.DataResidency
		*out = new(ModelEndpointResidency)
		(*in).DeepCopyInto(*out)
	}
	if in.Quota != nil {
		in, out := &in.Quota, &out.Quota
		*out = new(ModelEndpointQuota)
		(*in).DeepCopyInto(*out)
	}
	if in.Privacy != nil {
		in, out := &in.Privacy, &out.Privacy
		*out = new(ModelEndpointPrivacy)
		(*in).DeepCopyInto(*out)
	}
	if in.Fallback != nil {
		in, out := &in.Fallback, &out.Fallback
		*out = make([]sharedv1alpha1.ResourceRef, len(*in))
		copy(*out, *in)
	}
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(ModelEndpointDeployment)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelEndpointSpec.
func (in *ModelEndpointSpec) DeepCopy() *ModelEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(ModelEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelEndpointStatus) DeepCopyInto(out *ModelEndpointStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Healthy != nil {
		in, out := &in.Healthy, &out.Healthy
		*out = new(bool)
		**out = **in
	}
	if in.LastProbeAt != nil {
		in, out := &in.LastProbeAt, &out.LastProbeAt
		*out = (*in).DeepCopy()
	}
	if in.CurrentTpm != nil {
		in, out := &in.CurrentTpm, &out.CurrentTpm
		*out = new(int64)
		**out = **in
	}
	if in.CurrentRpm != nil {
		in, out := &in.CurrentRpm, &out.CurrentRpm
		*out = new(int64)
		**out = **in
	}
	if in.ErrorRate24h != nil {
		in, out := &in.ErrorRate24h, &out.ErrorRate24h
		*out = new(float64)
		**out = **in
	}
	if in.AvgLatencyMs != nil {
		in, out := &in.AvgLatencyMs, &out.AvgLatencyMs
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelEndpointStatus.
func (in *ModelEndpointStatus) DeepCopy() *ModelEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(ModelEndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRouter) DeepCopyInto(out *ModelRouter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRouter.
func (in *ModelRouter) DeepCopy() *ModelRouter {
	if in == nil {
		return nil
	}
	out := new(ModelRouter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelRouter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRouterCache) DeepCopyInto(out *ModelRouterCache) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(sharedv1alpha1.Duration)
		**out = **in
	}
	if in.SimilarityThreshold != nil {
		in, out := &in.SimilarityThreshold, &out.SimilarityThreshold
		*out = new(float64)
		**out = **in
	}
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(sharedv1alpha1.ResourceRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRouterCache.
func (in *ModelRouterCache) DeepCopy() *ModelRouterCache {
	if in == nil {
		return nil
	}
	out := new(ModelRouterCache)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRouterDistribution) DeepCopyInto(out *ModelRouterDistribution) {
	*out = *in
	if in.Weight != nil {
		in, out := &in.Weight, &out.Weight
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRouterDistribution.
func (in *ModelRouterDistribution) DeepCopy() *ModelRouterDistribution {
	if in == nil {
		return nil
	}
	out := new(ModelRouterDistribution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRouterList) DeepCopyInto(out *ModelRouterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelRouter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRouterList.
func (in *ModelRouterList) DeepCopy() *ModelRouterList {
	if in == nil {
		return nil
	}
	out := new(ModelRouterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelRouterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRouterRule) DeepCopyInto(out *ModelRouterRule) {
	*out = *in
	if in.When != nil {
		in, out := &in.When, &out.When
		*out = new(ModelRouterRuleWhen)
		(*in).DeepCopyInto(*out)
	}
	if in.Weight != nil {
		in, out := &in.Weight, &out.Weight
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRouterRule.
func (in *ModelRouterRule) DeepCopy() *ModelRouterRule {
	if in == nil {
		return nil
	}
	out := new(ModelRouterRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRouterRuleWhen) DeepCopyInto(out *ModelRouterRuleWhen) {
	*out = *in
	if in.ContextLengthMin != nil {
		in, out := &in.ContextLengthMin, &out.ContextLengthMin
		*out = new(int32)
		**out = **in
	}
	if in.CostSensitive != nil {
		in, out := &in.CostSensitive, &out.CostSensitive
		*out = new(bool)
		**out = **in
	}
	if in.LatencySensitive != nil {
		in, out := &in.LatencySensitive, &out.LatencySensitive
		*out = new(bool)
		**out = **in
	}
	if in.Compliance != nil {
		in, out := &in.Compliance, &out.Compliance
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRouterRuleWhen.
func (in *ModelRouterRuleWhen) DeepCopy() *ModelRouterRuleWhen {
	if in == nil {
		return nil
	}
	out := new(ModelRouterRuleWhen)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRouterSpec) DeepCopyInto(out *ModelRouterSpec) {
	*out = *in
	if in.DefaultEndpoint != nil {
		in, out := &in.DefaultEndpoint, &out.DefaultEndpoint
		*out = new(sharedv1alpha1.ResourceRef)
		**out = **in
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]ModelRouterRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Cache != nil {
		in, out := &in.Cache, &out.Cache
		*out = new(ModelRouterCache)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRouterSpec.
func (in *ModelRouterSpec) DeepCopy() *ModelRouterSpec {
	if in == nil {
		return nil
	}
	out := new(ModelRouterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRouterStatus) DeepCopyInto(out *ModelRouterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CacheHitRate != nil {
		in, out := &in.CacheHitRate, &out.CacheHitRate
		*out = new(float64)
		**out = **in
	}
	if in.Distribution != nil {
		in, out := &in.Distribution, &out.Distribution
		*out = make([]ModelRouterDistribution, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRouterStatus.
func (in *ModelRouterStatus) DeepCopy() *ModelRouterStatus {
	if in == nil {
		return nil
	}
	out := new(ModelRouterStatus)
	in.DeepCopyInto(out)
	return out
}
