//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	sharedv1alpha1 "github.com/ai-keeper/ai-keeper/api/shared/v1alpha1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PricingSpec) DeepCopyInto(out *PricingSpec) {
	*out = *in
	if in.Amount != nil {
		in, out := &in.Amount, &out.Amount
		*out = new(sharedv1alpha1.MoneyAmount)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PricingSpec.
func (in *PricingSpec) DeepCopy() *PricingSpec {
	if in == nil {
		return nil
	}
	out := new(PricingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublisherInfo) DeepCopyInto(out *PublisherInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublisherInfo.
func (in *PublisherInfo) DeepCopy() *PublisherInfo {
	if in == nil {
		return nil
	}
	out := new(PublisherInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Screenshot) DeepCopyInto(out *Screenshot) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Screenshot.
func (in *Screenshot) DeepCopy() *Screenshot {
	if in == nil {
		return nil
	}
	out := new(Screenshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillListing) DeepCopyInto(out *SkillListing) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillListing.
func (in *SkillListing) DeepCopy() *SkillListing {
	if in == nil {
		return nil
	}
	out := new(SkillListing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SkillListing) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillListingList) DeepCopyInto(out *SkillListingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SkillListing, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillListingList.
func (in *SkillListingList) DeepCopy() *SkillListingList {
	if in == nil {
		return nil
	}
	out := new(SkillListingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SkillListingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillListingSpec) DeepCopyInto(out *SkillListingSpec) {
	*out = *in
	out.Publisher = in.Publisher
	in.Pricing.DeepCopyInto(&out.Pricing)
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Screenshots != nil {
		in, out := &in.Screenshots, &out.Screenshots
		*out = make([]Screenshot, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillListingSpec.
func (in *SkillListingSpec) DeepCopy() *SkillListingSpec {
	if in == nil {
		return nil
	}
	out := new(SkillListingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillListingStatus) DeepCopyInto(out *SkillListingStatus) {
	*out = *in
	if in.Revenue != nil {
		in, out := &in.Revenue, &out.Revenue
		*out = new(sharedv1alpha1.MoneyAmount)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillListingStatus.
func (in *SkillListingStatus) DeepCopy() *SkillListingStatus {
	if in == nil {
		return nil
	}
	out := new(SkillListingStatus)
	in.DeepCopyInto(out)
	return out
}
