apiVersion: core.ai-keeper.io/v1alpha1
kind: ServiceAccount
metadata:
  name: gov-credit-sa
  namespace: gov-credit-dept
spec:
  displayName: Gov-Credit Pack Service Account
  allowOnBehalfOf: true
  tokenLifetime: 15m
  audiences:
    - aik-gateway
    - gov-credit-api
    - policy-query-engine
  authentication:
    method: sm2-certificate
    certRef: ref://secret/gov-credit-sm2-cert
