//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	sharedv1alpha1 "github.com/ai-keeper/ai-keeper/api/shared/v1alpha1"
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSource) DeepCopyInto(out *DataSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSource.
func (in *DataSource) DeepCopy() *DataSource {
	if in == nil {
		return nil
	}
	out := new(DataSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSourceACL) DeepCopyInto(out *DataSourceACL) {
	*out = *in
	if in.PolicyRef != nil {
		in, out := &in.PolicyRef, &out.PolicyRef
		*out = new(sharedv1alpha1.ResourceRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceACL.
func (in *DataSourceACL) DeepCopy() *DataSourceACL {
	if in == nil {
		return nil
	}
	out := new(DataSourceACL)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSourceAuthentication) DeepCopyInto(out *DataSourceAuthentication) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(DataSourceSecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceAuthentication.
func (in *DataSourceAuthentication) DeepCopy() *DataSourceAuthentication {
	if in == nil {
		return nil
	}
	out := new(DataSourceAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSourceConnector) DeepCopyInto(out *DataSourceConnector) {
	*out = *in
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(sharedv1alpha1.ResourceRef)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceConnector.
func (in *DataSourceConnector) DeepCopy() *DataSourceConnector {
	if in == nil {
		return nil
	}
	out := new(DataSourceConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSourceGovernance) DeepCopyInto(out *DataSourceGovernance) {
	*out = *in
	in.GovernanceBlock.DeepCopyInto(&out.GovernanceBlock)
	if in.Retention != nil {
		in, out := &in.Retention, &out.Retention
		*out = new(sharedv1alpha1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceGovernance.
func (in *DataSourceGovernance) DeepCopy() *DataSourceGovernance {
	if in == nil {
		return nil
	}
	out := new(DataSourceGovernance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSourceList) DeepCopyInto(out *DataSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DataSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceList.
func (in *DataSourceList) DeepCopy() *DataSourceList {
	if in == nil {
		return nil
	}
	out := new(DataSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSourceSecretRef) DeepCopyInto(out *DataSourceSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceSecretRef.
func (in *DataSourceSecretRef) DeepCopy() *DataSourceSecretRef {
	if in == nil {
		return nil
	}
	out := new(DataSourceSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSourceSpec) DeepCopyInto(out *DataSourceSpec) {
	*out = *in
	in.Connector.DeepCopyInto(&out.Connector)
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = new(DataSourceAuthentication)
		(*in).DeepCopyInto(*out)
	}
	if in.ACL != nil {
		in, out := &in.ACL, &out.ACL
		*out = new(DataSourceACL)
		(*in).DeepCopyInto(*out)
	}
	if in.Governance != nil {
		in, out := &in.Governance, &out.Governance
		*out = new(DataSourceGovernance)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceSpec.
func (in *DataSourceSpec) DeepCopy() *DataSourceSpec {
	if in == nil {
		return nil
	}
	out := new(DataSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSourceStatus) DeepCopyInto(out *DataSourceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Connected != nil {
		in, out := &in.Connected, &out.Connected
		*out = new(bool)
		**out = **in
	}
	if in.LastSyncAt != nil {
		in, out := &in.LastSyncAt, &out.LastSyncAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceStatus.
func (in *DataSourceStatus) DeepCopy() *DataSourceStatus {
	if in == nil {
		return nil
	}
	out := new(DataSourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KBACL) DeepCopyInto(out *KBACL) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KBACL.
func (in *KBACL) DeepCopy() *KBACL {
	if in == nil {
		return nil
	}
	out := new(KBACL)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KBChunking) DeepCopyInto(out *KBChunking) {
	*out = *in
	if in.MaxTokens != nil {
		in, out := &in.MaxTokens, &out.MaxTokens
		*out = new(int32)
		**out = **in
	}
	if in.Overlap != nil {
		in, out := &in.Overlap, &out.Overlap
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KBChunking.
func (in *KBChunking) DeepCopy() *KBChunking {
	if in == nil {
		return nil
	}
	out := new(KBChunking)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KBEmbedding) DeepCopyInto(out *KBEmbedding) {
	*out = *in
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(sharedv1alpha1.ResourceRef)
		**out = **in
	}
	if in.Dimensions != nil {
		in, out := &in.Dimensions, &out.Dimensions
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KBEmbedding.
func (in *KBEmbedding) DeepCopy() *KBEmbedding {
	if in == nil {
		return nil
	}
	out := new(KBEmbedding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KBGovernance) DeepCopyInto(out *KBGovernance) {
	*out = *in
	in.GovernanceBlock.DeepCopyInto(&out.GovernanceBlock)
	if in.Retention != nil {
		in, out := &in.Retention, &out.Retention
		*out = new(sharedv1alpha1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KBGovernance.
func (in *KBGovernance) DeepCopy() *KBGovernance {
	if in == nil {
		return nil
	}
	out := new(KBGovernance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KBIndex) DeepCopyInto(out *KBIndex) {
	*out = *in
	if in.GraphStore != nil {
		in, out := &in.GraphStore, &out.GraphStore
		*out = new(sharedv1alpha1.ResourceRef)
		**out = **in
	}
	if in.FullTextStore != nil {
		in, out := &in.FullTextStore, &out.FullTextStore
		*out = new(sharedv1alpha1.ResourceRef)
		**out = **in
	}
	if in.HybridSearch != nil {
		in, out := &in.HybridSearch, &out.HybridSearch
		*out = new(bool)
		**out = **in
	}
	if in.MultiTenant != nil {
		in, out := &in.MultiTenant, &out.MultiTenant
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KBIndex.
func (in *KBIndex) DeepCopy() *KBIndex {
	if in == nil {
		return nil
	}
	out := new(KBIndex)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KBPipeline) DeepCopyInto(out *KBPipeline) {
	*out = *in
	if in.Chunking != nil {
		in, out := &in.Chunking, &out.Chunking
		*out = new(KBChunking)
		(*in).DeepCopyInto(*out)
	}
	if in.Embedding != nil {
		in, out := &in.Embedding, &out.Embedding
		*out = new(KBEmbedding)
		(*in).DeepCopyInto(*out)
	}
	if in.Enrichment != nil {
		in, out := &in.Enrichment, &out.Enrichment
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KBPipeline.
func (in *KBPipeline) DeepCopy() *KBPipeline {
	if in == nil {
		return nil
	}
	out := new(KBPipeline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KBQualityMetrics) DeepCopyInto(out *KBQualityMetrics) {
	*out = *in
	if in.AvgRecall != nil {
		in, out := &in.AvgRecall, &out.AvgRecall
		*out = new(float64)
		**out = **in
	}
	if in.AvgMRR != nil {
		in, out := &in.AvgMRR, &out.AvgMRR
		*out = new(float64)
		**out = **in
	}
	if in.LastEvalAt != nil {
		in, out := &in.LastEvalAt, &out.LastEvalAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KBQualityMetrics.
func (in *KBQualityMetrics) DeepCopy() *KBQualityMetrics {
	if in == nil {
		return nil
	}
	out := new(KBQualityMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KBRetrieval) DeepCopyInto(out *KBRetrieval) {
	*out = *in
	if in.TopK != nil {
		in, out := &in.TopK, &out.TopK
		*out = new(int32)
		**out = **in
	}
	if in.Reranker != nil {
		in, out := &in.Reranker, &out.Reranker
		*out = new(sharedv1alpha1.ResourceRef)
		**out = **in
	}
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KBRetrieval.
func (in *KBRetrieval) DeepCopy() *KBRetrieval {
	if in == nil {
		return nil
	}
	out := new(KBRetrieval)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KBSource) DeepCopyInto(out *KBSource) {
	*out = *in
	if in.Sync != nil {
		in, out := &in.Sync, &out.Sync
		*out = new(KBSourceSync)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KBSource.
func (in *KBSource) DeepCopy() *KBSource {
	if in == nil {
		return nil
	}
	out := new(KBSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KBSourceSync) DeepCopyInto(out *KBSourceSync) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KBSourceSync.
func (in *KBSourceSync) DeepCopy() *KBSourceSync {
	if in == nil {
		return nil
	}
	out := new(KBSourceSync)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBase) DeepCopyInto(out *KnowledgeBase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBase.
func (in *KnowledgeBase) DeepCopy() *KnowledgeBase {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KnowledgeBase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBaseList) DeepCopyInto(out *KnowledgeBaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KnowledgeBase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBaseList.
func (in *KnowledgeBaseList) DeepCopy() *KnowledgeBaseList {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KnowledgeBaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBaseSpec) DeepCopyInto(out *KnowledgeBaseSpec) {
	*out = *in
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]KBSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Pipeline.DeepCopyInto(&out.Pipeline)
	in.Index.DeepCopyInto(&out.Index)
	if in.Retrieval != nil {
		in, out := &in.Retrieval, &out.Retrieval
		*out = new(KBRetrieval)
		(*in).DeepCopyInto(*out)
	}
	if in.ACL != nil {
		in, out := &in.ACL, &out.ACL
		*out = new(KBACL)
		**out = **in
	}
	if in.Governance != nil {
		in, out := &in.Governance, &out.Governance
		*out = new(KBGovernance)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBaseSpec.
func (in *KnowledgeBaseSpec) DeepCopy() *KnowledgeBaseSpec {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBaseStatus) DeepCopyInto(out *KnowledgeBaseStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastIndexedAt != nil {
		in, out := &in.LastIndexedAt, &out.LastIndexedAt
		*out = (*in).DeepCopy()
	}
	if in.QualityMetrics != nil {
		in, out := &in.QualityMetrics, &out.QualityMetrics
		*out = new(KBQualityMetrics)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBaseStatus.
func (in *KnowledgeBaseStatus) DeepCopy() *KnowledgeBaseStatus {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBaseStatus)
	in.DeepCopyInto(out)
	return out
}
