//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	sharedv1alpha1 "github.com/ai-keeper/ai-keeper/api/shared/v1alpha1"
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Skill) DeepCopyInto(out *Skill) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Skill.
func (in *Skill) DeepCopy() *Skill {
	if in == nil {
		return nil
	}
	out := new(Skill)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Skill) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillDataSourceDep) DeepCopyInto(out *SkillDataSourceDep) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillDataSourceDep.
func (in *SkillDataSourceDep) DeepCopy() *SkillDataSourceDep {
	if in == nil {
		return nil
	}
	out := new(SkillDataSourceDep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillDeprecation) DeepCopyInto(out *SkillDeprecation) {
	*out = *in
	if in.Successor != nil {
		in, out := &in.Successor, &out.Successor
		*out = new(sharedv1alpha1.ResourceRef)
		**out = **in
	}
	if in.SunsetAt != nil {
		in, out := &in.SunsetAt, &out.SunsetAt
		*out = (*in).DeepCopy()
	}
	if in.MigrationGuide != nil {
		in, out := &in.MigrationGuide, &out.MigrationGuide
		*out = new(sharedv1alpha1.ResourceRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillDeprecation.
func (in *SkillDeprecation) DeepCopy() *SkillDeprecation {
	if in == nil {
		return nil
	}
	out := new(SkillDeprecation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillEvalResults) DeepCopyInto(out *SkillEvalResults) {
	*out = *in
	if in.LastRunAt != nil {
		in, out := &in.LastRunAt, &out.LastRunAt
		*out = (*in).DeepCopy()
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Passed != nil {
		in, out := &in.Passed, &out.Passed
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillEvalResults.
func (in *SkillEvalResults) DeepCopy() *SkillEvalResults {
	if in == nil {
		return nil
	}
	out := new(SkillEvalResults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillEvaluation) DeepCopyInto(out *SkillEvaluation) {
	*out = *in
	if in.EvalSet != nil {
		in, out := &in.EvalSet, &out.EvalSet
		*out = new(sharedv1alpha1.ResourceRef)
		**out = **in
	}
	if in.RedTeamSet != nil {
		in, out := &in.RedTeamSet, &out.RedTeamSet
		*out = new(sharedv1alpha1.ResourceRef)
		**out = **in
	}
	if in.Gates != nil {
		in, out := &in.Gates, &out.Gates
		*out = make(map[string]map[string]string, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillEvaluation.
func (in *SkillEvaluation) DeepCopy() *SkillEvaluation {
	if in == nil {
		return nil
	}
	out := new(SkillEvaluation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillExample) DeepCopyInto(out *SkillExample) {
	*out = *in
	if in.Input != nil {
		in, out := &in.Input, &out.Input
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillExample.
func (in *SkillExample) DeepCopy() *SkillExample {
	if in == nil {
		return nil
	}
	out := new(SkillExample)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillHealth) DeepCopyInto(out *SkillHealth) {
	*out = *in
	if in.P95LatencyMs != nil {
		in, out := &in.P95LatencyMs, &out.P95LatencyMs
		*out = new(int32)
		**out = **in
	}
	if in.SuccessRate != nil {
		in, out := &in.SuccessRate, &out.SuccessRate
		*out = new(float64)
		**out = **in
	}
	if in.CostPerCallUsd != nil {
		in, out := &in.CostPerCallUsd, &out.CostPerCallUsd
		*out = new(sharedv1alpha1.MoneyAmount)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillHealth.
func (in *SkillHealth) DeepCopy() *SkillHealth {
	if in == nil {
		return nil
	}
	out := new(SkillHealth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillIO) DeepCopyInto(out *SkillIO) {
	*out = *in
	if in.Schema != nil {
		in, out := &in.Schema, &out.Schema
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillIO.
func (in *SkillIO) DeepCopy() *SkillIO {
	if in == nil {
		return nil
	}
	out := new(SkillIO)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillImplementation) DeepCopyInto(out *SkillImplementation) {
	*out = *in
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(SkillRuntime)
		**out = **in
	}
	if in.PromptTemplate != nil {
		in, out := &in.PromptTemplate, &out.PromptTemplate
		*out = new(SkillPromptTemplate)
		(*in).DeepCopyInto(*out)
	}
	if in.Requires != nil {
		in, out := &in.Requires, &out.Requires
		*out = new(SkillRequires)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillImplementation.
func (in *SkillImplementation) DeepCopy() *SkillImplementation {
	if in == nil {
		return nil
	}
	out := new(SkillImplementation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillInterface) DeepCopyInto(out *SkillInterface) {
	*out = *in
	in.Input.DeepCopyInto(&out.Input)
	in.Output.DeepCopyInto(&out.Output)
	if in.Examples != nil {
		in, out := &in.Examples, &out.Examples
		*out = make([]SkillExample, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillInterface.
func (in *SkillInterface) DeepCopy() *SkillInterface {
	if in == nil {
		return nil
	}
	out := new(SkillInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillLifecycle) DeepCopyInto(out *SkillLifecycle) {
	*out = *in
	if in.Deprecation != nil {
		in, out := &in.Deprecation, &out.Deprecation
		*out = new(SkillDeprecation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillLifecycle.
func (in *SkillLifecycle) DeepCopy() *SkillLifecycle {
	if in == nil {
		return nil
	}
	out := new(SkillLifecycle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillList) DeepCopyInto(out *SkillList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Skill, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillList.
func (in *SkillList) DeepCopy() *SkillList {
	if in == nil {
		return nil
	}
	out := new(SkillList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SkillList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillModelDep) DeepCopyInto(out *SkillModelDep) {
	*out = *in
	if in.Fallback != nil {
		in, out := &in.Fallback, &out.Fallback
		*out = make([]sharedv1alpha1.ResourceRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillModelDep.
func (in *SkillModelDep) DeepCopy() *SkillModelDep {
	if in == nil {
		return nil
	}
	out := new(SkillModelDep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillPromptTemplate) DeepCopyInto(out *SkillPromptTemplate) {
	*out = *in
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(sharedv1alpha1.ResourceRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillPromptTemplate.
func (in *SkillPromptTemplate) DeepCopy() *SkillPromptTemplate {
	if in == nil {
		return nil
	}
	out := new(SkillPromptTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillRequires) DeepCopyInto(out *SkillRequires) {
	*out = *in
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make([]SkillModelDep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tools != nil {
		in, out := &in.Tools, &out.Tools
		*out = make([]SkillToolDep, len(*in))
		copy(*out, *in)
	}
	if in.DataSources != nil {
		in, out := &in.DataSources, &out.DataSources
		*out = make([]SkillDataSourceDep, len(*in))
		copy(*out, *in)
	}
	if in.Skills != nil {
		in, out := &in.Skills, &out.Skills
		*out = make([]SkillSubSkillDep, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillRequires.
func (in *SkillRequires) DeepCopy() *SkillRequires {
	if in == nil {
		return nil
	}
	out := new(SkillRequires)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillResolvedDependencies) DeepCopyInto(out *SkillResolvedDependencies) {
	*out = *in
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make([]SkillResolvedModel, len(*in))
		copy(*out, *in)
	}
	if in.Tools != nil {
		in, out := &in.Tools, &out.Tools
		*out = make([]sharedv1alpha1.ResourceRef, len(*in))
		copy(*out, *in)
	}
	if in.DataSources != nil {
		in, out := &in.DataSources, &out.DataSources
		*out = make([]sharedv1alpha1.ResourceRef, len(*in))
		copy(*out, *in)
	}
	if in.Skills != nil {
		in, out := &in.Skills, &out.Skills
		*out = make([]sharedv1alpha1.ResourceRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillResolvedDependencies.
func (in *SkillResolvedDependencies) DeepCopy() *SkillResolvedDependencies {
	if in == nil {
		return nil
	}
	out := new(SkillResolvedDependencies)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillResolvedModel) DeepCopyInto(out *SkillResolvedModel) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillResolvedModel.
func (in *SkillResolvedModel) DeepCopy() *SkillResolvedModel {
	if in == nil {
		return nil
	}
	out := new(SkillResolvedModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillRuntime) DeepCopyInto(out *SkillRuntime) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillRuntime.
func (in *SkillRuntime) DeepCopy() *SkillRuntime {
	if in == nil {
		return nil
	}
	out := new(SkillRuntime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillSpec) DeepCopyInto(out *SkillSpec) {
	*out = *in
	in.Interface.DeepCopyInto(&out.Interface)
	in.Implementation.DeepCopyInto(&out.Implementation)
	if in.Governance != nil {
		in, out := &in.Governance, &out.Governance
		*out = new(sharedv1alpha1.GovernanceBlock)
		(*in).DeepCopyInto(*out)
	}
	if in.Cost != nil {
		in, out := &in.Cost, &out.Cost
		*out = new(sharedv1alpha1.CostBlock)
		(*in).DeepCopyInto(*out)
	}
	if in.SLO != nil {
		in, out := &in.SLO, &out.SLO
		*out = new(sharedv1alpha1.SLOBlock)
		(*in).DeepCopyInto(*out)
	}
	if in.Reliability != nil {
		in, out := &in.Reliability, &out.Reliability
		*out = new(sharedv1alpha1.ReliabilityBlock)
		(*in).DeepCopyInto(*out)
	}
	if in.Evaluation != nil {
		in, out := &in.Evaluation, &out.Evaluation
		*out = new(SkillEvaluation)
		(*in).DeepCopyInto(*out)
	}
	if in.Lifecycle != nil {
		in, out := &in.Lifecycle, &out.Lifecycle
		*out = new(SkillLifecycle)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillSpec.
func (in *SkillSpec) DeepCopy() *SkillSpec {
	if in == nil {
		return nil
	}
	out := new(SkillSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillStatus) DeepCopyInto(out *SkillStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Health != nil {
		in, out := &in.Health, &out.Health
		*out = new(SkillHealth)
		(*in).DeepCopyInto(*out)
	}
	if in.EvalResults != nil {
		in, out := &in.EvalResults, &out.EvalResults
		*out = new(SkillEvalResults)
		(*in).DeepCopyInto(*out)
	}
	if in.ResolvedDependencies != nil {
		in, out := &in.ResolvedDependencies, &out.ResolvedDependencies
		*out = new(SkillResolvedDependencies)
		(*in).DeepCopyInto(*out)
	}
	if in.ReferencingAgents != nil {
		in, out := &in.ReferencingAgents, &out.ReferencingAgents
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillStatus.
func (in *SkillStatus) DeepCopy() *SkillStatus {
	if in == nil {
		return nil
	}
	out := new(SkillStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillSubSkillDep) DeepCopyInto(out *SkillSubSkillDep) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillSubSkillDep.
func (in *SkillSubSkillDep) DeepCopy() *SkillSubSkillDep {
	if in == nil {
		return nil
	}
	out := new(SkillSubSkillDep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillToolDep) DeepCopyInto(out *SkillToolDep) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillToolDep.
func (in *SkillToolDep) DeepCopy() *SkillToolDep {
	if in == nil {
		return nil
	}
	out := new(SkillToolDep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tool) DeepCopyInto(out *Tool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tool.
func (in *Tool) DeepCopy() *Tool {
	if in == nil {
		return nil
	}
	out := new(Tool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Tool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolAuthentication) DeepCopyInto(out *ToolAuthentication) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(ToolSecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolAuthentication.
func (in *ToolAuthentication) DeepCopy() *ToolAuthentication {
	if in == nil {
		return nil
	}
	out := new(ToolAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolCost) DeepCopyInto(out *ToolCost) {
	*out = *in
	if in.PerCallUsd != nil {
		in, out := &in.PerCallUsd, &out.PerCallUsd
		*out = new(sharedv1alpha1.MoneyAmount)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolCost.
func (in *ToolCost) DeepCopy() *ToolCost {
	if in == nil {
		return nil
	}
	out := new(ToolCost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolGovernance) DeepCopyInto(out *ToolGovernance) {
	*out = *in
	in.GovernanceBlock.DeepCopyInto(&out.GovernanceBlock)
	if in.RequiresApproval != nil {
		in, out := &in.RequiresApproval, &out.RequiresApproval
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolGovernance.
func (in *ToolGovernance) DeepCopy() *ToolGovernance {
	if in == nil {
		return nil
	}
	out := new(ToolGovernance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolList) DeepCopyInto(out *ToolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Tool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolList.
func (in *ToolList) DeepCopy() *ToolList {
	if in == nil {
		return nil
	}
	out := new(ToolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ToolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolRateLimit) DeepCopyInto(out *ToolRateLimit) {
	*out = *in
	if in.PerAgentPerMinute != nil {
		in, out := &in.PerAgentPerMinute, &out.PerAgentPerMinute
		*out = new(int32)
		**out = **in
	}
	if in.PerTenantPerMinute != nil {
		in, out := &in.PerTenantPerMinute, &out.PerTenantPerMinute
		*out = new(int32)
		**out = **in
	}
	if in.Burst != nil {
		in, out := &in.Burst, &out.Burst
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolRateLimit.
func (in *ToolRateLimit) DeepCopy() *ToolRateLimit {
	if in == nil {
		return nil
	}
	out := new(ToolRateLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolSchema) DeepCopyInto(out *ToolSchema) {
	*out = *in
	if in.Input != nil {
		in, out := &in.Input, &out.Input
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolSchema.
func (in *ToolSchema) DeepCopy() *ToolSchema {
	if in == nil {
		return nil
	}
	out := new(ToolSchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolSecretRef) DeepCopyInto(out *ToolSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolSecretRef.
func (in *ToolSecretRef) DeepCopy() *ToolSecretRef {
	if in == nil {
		return nil
	}
	out := new(ToolSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolSpec) DeepCopyInto(out *ToolSpec) {
	*out = *in
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = new(ToolAuthentication)
		(*in).DeepCopyInto(*out)
	}
	in.Schema.DeepCopyInto(&out.Schema)
	in.Governance.DeepCopyInto(&out.Governance)
	if in.Cost != nil {
		in, out := &in.Cost, &out.Cost
		*out = new(ToolCost)
		(*in).DeepCopyInto(*out)
	}
	if in.RateLimit != nil {
		in, out := &in.RateLimit, &out.RateLimit
		*out = new(ToolRateLimit)
		(*in).DeepCopyInto(*out)
	}
	if in.Reliability != nil {
		in, out := &in.Reliability, &out.Reliability
		*out = new(sharedv1alpha1.ReliabilityBlock)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolSpec.
func (in *ToolSpec) DeepCopy() *ToolSpec {
	if in == nil {
		return nil
	}
	out := new(ToolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolStatus) DeepCopyInto(out *ToolStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Reachable != nil {
		in, out := &in.Reachable, &out.Reachable
		*out = new(bool)
		**out = **in
	}
	if in.LastProbeAt != nil {
		in, out := &in.LastProbeAt, &out.LastProbeAt
		*out = (*in).DeepCopy()
	}
	if in.ErrorRate24h != nil {
		in, out := &in.ErrorRate24h, &out.ErrorRate24h
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolStatus.
func (in *ToolStatus) DeepCopy() *ToolStatus {
	if in == nil {
		return nil
	}
	out := new(ToolStatus)
	in.DeepCopyInto(out)
	return out
}
