# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from aip.v1 import audit_pb2 as aip_dot_v1_dot_audit__pb2


class AuditSinkServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Emit = channel.unary_unary(
                '/aip.v1.AuditSinkService/Emit',
                request_serializer=aip_dot_v1_dot_audit__pb2.EmitRequest.SerializeToString,
                response_deserializer=aip_dot_v1_dot_audit__pb2.EmitResponse.FromString,
                _registered_method=True)
        self.Query = channel.unary_stream(
                '/aip.v1.AuditSinkService/Query',
                request_serializer=aip_dot_v1_dot_audit__pb2.QueryRequest.SerializeToString,
                response_deserializer=aip_dot_v1_dot_audit__pb2.AuditEvent.FromString,
                _registered_method=True)


class AuditSinkServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Emit(self, request, context):
        """Emit one AuditEvent. Producer-side at-least-once; Sink-side dedup by
        (invocation_id, step_id) (B12 / F22).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Server-streamed query. Read-only (Property 9 — immutability).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuditSinkServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Emit': grpc.unary_unary_rpc_method_handler(
                    servicer.Emit,
                    request_deserializer=aip_dot_v1_dot_audit__pb2.EmitRequest.FromString,
                    response_serializer=aip_dot_v1_dot_audit__pb2.EmitResponse.SerializeToString,
            ),
            'Query': grpc.unary_stream_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=aip_dot_v1_dot_audit__pb2.QueryRequest.FromString,
                    response_serializer=aip_dot_v1_dot_audit__pb2.AuditEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aip.v1.AuditSinkService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aip.v1.AuditSinkService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuditSinkService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Emit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aip.v1.AuditSinkService/Emit',
            aip_dot_v1_dot_audit__pb2.EmitRequest.SerializeToString,
            aip_dot_v1_dot_audit__pb2.EmitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aip.v1.AuditSinkService/Query',
            aip_dot_v1_dot_audit__pb2.QueryRequest.SerializeToString,
            aip_dot_v1_dot_audit__pb2.AuditEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
