# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from aip.v1 import cost_pb2 as aip_dot_v1_dot_cost__pb2


class CostServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Compute = channel.unary_unary(
                '/aip.v1.CostService/Compute',
                request_serializer=aip_dot_v1_dot_cost__pb2.ComputeRequest.SerializeToString,
                response_deserializer=aip_dot_v1_dot_cost__pb2.ComputeResponse.FromString,
                _registered_method=True)
        self.Record = channel.unary_unary(
                '/aip.v1.CostService/Record',
                request_serializer=aip_dot_v1_dot_cost__pb2.RecordRequest.SerializeToString,
                response_deserializer=aip_dot_v1_dot_cost__pb2.RecordResponse.FromString,
                _registered_method=True)
        self.Balance = channel.unary_unary(
                '/aip.v1.CostService/Balance',
                request_serializer=aip_dot_v1_dot_cost__pb2.BalanceRequest.SerializeToString,
                response_deserializer=aip_dot_v1_dot_cost__pb2.BalanceResponse.FromString,
                _registered_method=True)


class CostServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Compute(self, request, context):
        """Pure cost calculation (Property 31 — same input ⇒ same output, ≥ 0).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Record(self, request, context):
        """Persist usage + debit Redis budget counters (B11 / A8).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Balance(self, request, context):
        """Read current balance for one or more scopes (Console / aipctl).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CostServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Compute': grpc.unary_unary_rpc_method_handler(
                    servicer.Compute,
                    request_deserializer=aip_dot_v1_dot_cost__pb2.ComputeRequest.FromString,
                    response_serializer=aip_dot_v1_dot_cost__pb2.ComputeResponse.SerializeToString,
            ),
            'Record': grpc.unary_unary_rpc_method_handler(
                    servicer.Record,
                    request_deserializer=aip_dot_v1_dot_cost__pb2.RecordRequest.FromString,
                    response_serializer=aip_dot_v1_dot_cost__pb2.RecordResponse.SerializeToString,
            ),
            'Balance': grpc.unary_unary_rpc_method_handler(
                    servicer.Balance,
                    request_deserializer=aip_dot_v1_dot_cost__pb2.BalanceRequest.FromString,
                    response_serializer=aip_dot_v1_dot_cost__pb2.BalanceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aip.v1.CostService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aip.v1.CostService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CostService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Compute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aip.v1.CostService/Compute',
            aip_dot_v1_dot_cost__pb2.ComputeRequest.SerializeToString,
            aip_dot_v1_dot_cost__pb2.ComputeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Record(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aip.v1.CostService/Record',
            aip_dot_v1_dot_cost__pb2.RecordRequest.SerializeToString,
            aip_dot_v1_dot_cost__pb2.RecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Balance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aip.v1.CostService/Balance',
            aip_dot_v1_dot_cost__pb2.BalanceRequest.SerializeToString,
            aip_dot_v1_dot_cost__pb2.BalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
