# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from aip.v1 import dlp_pb2 as aip_dot_v1_dot_dlp__pb2


class DlpServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Inspect = channel.unary_unary(
                '/aip.v1.DlpService/Inspect',
                request_serializer=aip_dot_v1_dot_dlp__pb2.InspectRequest.SerializeToString,
                response_deserializer=aip_dot_v1_dot_dlp__pb2.InspectResponse.FromString,
                _registered_method=True)


class DlpServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Inspect(self, request, context):
        """Inspect a single text payload (B4.1 / B4.2 / B4.3).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DlpServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Inspect': grpc.unary_unary_rpc_method_handler(
                    servicer.Inspect,
                    request_deserializer=aip_dot_v1_dot_dlp__pb2.InspectRequest.FromString,
                    response_serializer=aip_dot_v1_dot_dlp__pb2.InspectResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aip.v1.DlpService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aip.v1.DlpService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DlpService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Inspect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aip.v1.DlpService/Inspect',
            aip_dot_v1_dot_dlp__pb2.InspectRequest.SerializeToString,
            aip_dot_v1_dot_dlp__pb2.InspectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
