# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from aip.v1 import identity_pb2 as aip_dot_v1_dot_identity__pb2


class IdentityServiceStub(object):
    """Service --------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Verify = channel.unary_unary(
                '/aip.v1.IdentityService/Verify',
                request_serializer=aip_dot_v1_dot_identity__pb2.VerifyRequest.SerializeToString,
                response_deserializer=aip_dot_v1_dot_identity__pb2.VerifyResponse.FromString,
                _registered_method=True)
        self.Exchange = channel.unary_unary(
                '/aip.v1.IdentityService/Exchange',
                request_serializer=aip_dot_v1_dot_identity__pb2.ExchangeRequest.SerializeToString,
                response_deserializer=aip_dot_v1_dot_identity__pb2.ExchangeResponse.FromString,
                _registered_method=True)
        self.Revoke = channel.unary_unary(
                '/aip.v1.IdentityService/Revoke',
                request_serializer=aip_dot_v1_dot_identity__pb2.RevokeRequest.SerializeToString,
                response_deserializer=aip_dot_v1_dot_identity__pb2.RevokeResponse.FromString,
                _registered_method=True)


class IdentityServiceServicer(object):
    """Service --------------------------------------------------------------------

    """

    def Verify(self, request, context):
        """Verify an inbound OIDC / SAML / SPIFFE token (B3.2).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exchange(self, request, context):
        """RFC 8693 OBO Token Exchange. Used when Agent.spec.identity.representation
        .mode == "on_behalf_of" (B3.1, B3.3).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Revoke(self, request, context):
        """Revoke all outstanding tokens for a ServiceAccount (B3.5: must complete
        within 30 seconds of the SA being deleted/disabled).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IdentityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Verify': grpc.unary_unary_rpc_method_handler(
                    servicer.Verify,
                    request_deserializer=aip_dot_v1_dot_identity__pb2.VerifyRequest.FromString,
                    response_serializer=aip_dot_v1_dot_identity__pb2.VerifyResponse.SerializeToString,
            ),
            'Exchange': grpc.unary_unary_rpc_method_handler(
                    servicer.Exchange,
                    request_deserializer=aip_dot_v1_dot_identity__pb2.ExchangeRequest.FromString,
                    response_serializer=aip_dot_v1_dot_identity__pb2.ExchangeResponse.SerializeToString,
            ),
            'Revoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Revoke,
                    request_deserializer=aip_dot_v1_dot_identity__pb2.RevokeRequest.FromString,
                    response_serializer=aip_dot_v1_dot_identity__pb2.RevokeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aip.v1.IdentityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aip.v1.IdentityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IdentityService(object):
    """Service --------------------------------------------------------------------

    """

    @staticmethod
    def Verify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aip.v1.IdentityService/Verify',
            aip_dot_v1_dot_identity__pb2.VerifyRequest.SerializeToString,
            aip_dot_v1_dot_identity__pb2.VerifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exchange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aip.v1.IdentityService/Exchange',
            aip_dot_v1_dot_identity__pb2.ExchangeRequest.SerializeToString,
            aip_dot_v1_dot_identity__pb2.ExchangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Revoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aip.v1.IdentityService/Revoke',
            aip_dot_v1_dot_identity__pb2.RevokeRequest.SerializeToString,
            aip_dot_v1_dot_identity__pb2.RevokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
