# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from aip.v1 import pdp_pb2 as aip_dot_v1_dot_pdp__pb2


class PolicyDecisionServiceStub(object):
    """Service --------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Decide = channel.unary_unary(
                '/aip.v1.PolicyDecisionService/Decide',
                request_serializer=aip_dot_v1_dot_pdp__pb2.DecisionRequest.SerializeToString,
                response_deserializer=aip_dot_v1_dot_pdp__pb2.DecisionResponse.FromString,
                _registered_method=True)
        self.Watch = channel.unary_stream(
                '/aip.v1.PolicyDecisionService/Watch',
                request_serializer=aip_dot_v1_dot_pdp__pb2.BundleSubscribeRequest.SerializeToString,
                response_deserializer=aip_dot_v1_dot_pdp__pb2.BundleEvent.FromString,
                _registered_method=True)


class PolicyDecisionServiceServicer(object):
    """Service --------------------------------------------------------------------

    """

    def Decide(self, request, context):
        """Decide a single inbound action. PEP MUST fail-closed if this RPC times
        out within the 1s SLA (Requirement B2.8 / F6).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Watch(self, request, context):
        """Stream new bundle versions to PDP replicas (Requirement A5.5/A5.6).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PolicyDecisionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Decide': grpc.unary_unary_rpc_method_handler(
                    servicer.Decide,
                    request_deserializer=aip_dot_v1_dot_pdp__pb2.DecisionRequest.FromString,
                    response_serializer=aip_dot_v1_dot_pdp__pb2.DecisionResponse.SerializeToString,
            ),
            'Watch': grpc.unary_stream_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=aip_dot_v1_dot_pdp__pb2.BundleSubscribeRequest.FromString,
                    response_serializer=aip_dot_v1_dot_pdp__pb2.BundleEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aip.v1.PolicyDecisionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aip.v1.PolicyDecisionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PolicyDecisionService(object):
    """Service --------------------------------------------------------------------

    """

    @staticmethod
    def Decide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aip.v1.PolicyDecisionService/Decide',
            aip_dot_v1_dot_pdp__pb2.DecisionRequest.SerializeToString,
            aip_dot_v1_dot_pdp__pb2.DecisionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aip.v1.PolicyDecisionService/Watch',
            aip_dot_v1_dot_pdp__pb2.BundleSubscribeRequest.SerializeToString,
            aip_dot_v1_dot_pdp__pb2.BundleEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
