# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from aip.v1 import router_pb2 as aip_dot_v1_dot_router__pb2


class ModelRouterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Route = channel.unary_unary(
                '/aip.v1.ModelRouterService/Route',
                request_serializer=aip_dot_v1_dot_router__pb2.RouteRequest.SerializeToString,
                response_deserializer=aip_dot_v1_dot_router__pb2.RouteResponse.FromString,
                _registered_method=True)
        self.CompleteChat = channel.unary_stream(
                '/aip.v1.ModelRouterService/CompleteChat',
                request_serializer=aip_dot_v1_dot_router__pb2.ChatRequest.SerializeToString,
                response_deserializer=aip_dot_v1_dot_router__pb2.ChatChunk.FromString,
                _registered_method=True)


class ModelRouterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Route(self, request, context):
        """Resolve a logical alias to a concrete endpoint (B8.1 / B8.2).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteChat(self, request, context):
        """Streamed chat completion. Wraps endpoint client + semantic cache +
        fallback retries (B8.4 / B8.5 / B8.6).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelRouterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Route': grpc.unary_unary_rpc_method_handler(
                    servicer.Route,
                    request_deserializer=aip_dot_v1_dot_router__pb2.RouteRequest.FromString,
                    response_serializer=aip_dot_v1_dot_router__pb2.RouteResponse.SerializeToString,
            ),
            'CompleteChat': grpc.unary_stream_rpc_method_handler(
                    servicer.CompleteChat,
                    request_deserializer=aip_dot_v1_dot_router__pb2.ChatRequest.FromString,
                    response_serializer=aip_dot_v1_dot_router__pb2.ChatChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aip.v1.ModelRouterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aip.v1.ModelRouterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelRouterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Route(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aip.v1.ModelRouterService/Route',
            aip_dot_v1_dot_router__pb2.RouteRequest.SerializeToString,
            aip_dot_v1_dot_router__pb2.RouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aip.v1.ModelRouterService/CompleteChat',
            aip_dot_v1_dot_router__pb2.ChatRequest.SerializeToString,
            aip_dot_v1_dot_router__pb2.ChatChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
