# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from aip.v1 import runtime_pb2 as aip_dot_v1_dot_runtime__pb2


class AgentRuntimeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Invoke = channel.unary_stream(
                '/aip.v1.AgentRuntimeService/Invoke',
                request_serializer=aip_dot_v1_dot_runtime__pb2.InvokeRequest.SerializeToString,
                response_deserializer=aip_dot_v1_dot_runtime__pb2.InvokeEvent.FromString,
                _registered_method=True)


class AgentRuntimeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Invoke(self, request, context):
        """Server-streamed invocation. Clients receive one InvokeEvent per state
        transition; the stream MUST end with exactly one InvokeFinal (B5.6 /
        Property 8 — audit completeness invariant).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentRuntimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Invoke': grpc.unary_stream_rpc_method_handler(
                    servicer.Invoke,
                    request_deserializer=aip_dot_v1_dot_runtime__pb2.InvokeRequest.FromString,
                    response_serializer=aip_dot_v1_dot_runtime__pb2.InvokeEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aip.v1.AgentRuntimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aip.v1.AgentRuntimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentRuntimeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Invoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aip.v1.AgentRuntimeService/Invoke',
            aip_dot_v1_dot_runtime__pb2.InvokeRequest.SerializeToString,
            aip_dot_v1_dot_runtime__pb2.InvokeEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
