//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	sharedv1alpha1 "github.com/ai-keeper/ai-keeper/api/shared/v1alpha1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApprovalApprover) DeepCopyInto(out *ApprovalApprover) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApprovalApprover.
func (in *ApprovalApprover) DeepCopy() *ApprovalApprover {
	if in == nil {
		return nil
	}
	out := new(ApprovalApprover)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApprovalSpec) DeepCopyInto(out *ApprovalSpec) {
	*out = *in
	out.When = in.When
	out.Approver = in.Approver
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(sharedv1alpha1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApprovalSpec.
func (in *ApprovalSpec) DeepCopy() *ApprovalSpec {
	if in == nil {
		return nil
	}
	out := new(ApprovalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApprovalWhen) DeepCopyInto(out *ApprovalWhen) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApprovalWhen.
func (in *ApprovalWhen) DeepCopy() *ApprovalWhen {
	if in == nil {
		return nil
	}
	out := new(ApprovalWhen)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Budget) DeepCopyInto(out *Budget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Budget.
func (in *Budget) DeepCopy() *Budget {
	if in == nil {
		return nil
	}
	out := new(Budget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Budget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetAlert) DeepCopyInto(out *BudgetAlert) {
	*out = *in
	if in.Channels != nil {
		in, out := &in.Channels, &out.Channels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetAlert.
func (in *BudgetAlert) DeepCopy() *BudgetAlert {
	if in == nil {
		return nil
	}
	out := new(BudgetAlert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetCurrent) DeepCopyInto(out *BudgetCurrent) {
	*out = *in
	if in.Usd != nil {
		in, out := &in.Usd, &out.Usd
		*out = new(sharedv1alpha1.MoneyAmount)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetCurrent.
func (in *BudgetCurrent) DeepCopy() *BudgetCurrent {
	if in == nil {
		return nil
	}
	out := new(BudgetCurrent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetLimits) DeepCopyInto(out *BudgetLimits) {
	*out = *in
	if in.Usd != nil {
		in, out := &in.Usd, &out.Usd
		*out = new(sharedv1alpha1.MoneyAmount)
		**out = **in
	}
	if in.Tokens != nil {
		in, out := &in.Tokens, &out.Tokens
		*out = new(int64)
		**out = **in
	}
	if in.Calls != nil {
		in, out := &in.Calls, &out.Calls
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetLimits.
func (in *BudgetLimits) DeepCopy() *BudgetLimits {
	if in == nil {
		return nil
	}
	out := new(BudgetLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetList) DeepCopyInto(out *BudgetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Budget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetList.
func (in *BudgetList) DeepCopy() *BudgetList {
	if in == nil {
		return nil
	}
	out := new(BudgetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BudgetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetScope) DeepCopyInto(out *BudgetScope) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetScope.
func (in *BudgetScope) DeepCopy() *BudgetScope {
	if in == nil {
		return nil
	}
	out := new(BudgetScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetSpec) DeepCopyInto(out *BudgetSpec) {
	*out = *in
	out.Scope = in.Scope
	in.Limits.DeepCopyInto(&out.Limits)
	if in.Alerts != nil {
		in, out := &in.Alerts, &out.Alerts
		*out = make([]BudgetAlert, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Rollover != nil {
		in, out := &in.Rollover, &out.Rollover
		*out = new(bool)
		**out = **in
	}
	if in.HardCap != nil {
		in, out := &in.HardCap, &out.HardCap
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetSpec.
func (in *BudgetSpec) DeepCopy() *BudgetSpec {
	if in == nil {
		return nil
	}
	out := new(BudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetStatus) DeepCopyInto(out *BudgetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Current != nil {
		in, out := &in.Current, &out.Current
		*out = new(BudgetCurrent)
		(*in).DeepCopyInto(*out)
	}
	if in.PeriodStart != nil {
		in, out := &in.PeriodStart, &out.PeriodStart
		*out = (*in).DeepCopy()
	}
	if in.PeriodEnd != nil {
		in, out := &in.PeriodEnd, &out.PeriodEnd
		*out = (*in).DeepCopy()
	}
	if in.DaysRemaining != nil {
		in, out := &in.DaysRemaining, &out.DaysRemaining
		*out = new(int32)
		**out = **in
	}
	if in.ProjectedExhaustionAt != nil {
		in, out := &in.ProjectedExhaustionAt, &out.ProjectedExhaustionAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetStatus.
func (in *BudgetStatus) DeepCopy() *BudgetStatus {
	if in == nil {
		return nil
	}
	out := new(BudgetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionItem) DeepCopyInto(out *ConditionItem) {
	*out = *in
	if in.TimeWindow != nil {
		in, out := &in.TimeWindow, &out.TimeWindow
		*out = new(ConditionTimeWindow)
		**out = **in
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(ConditionLocation)
		(*in).DeepCopyInto(*out)
	}
	if in.DataClassificationCeiling != nil {
		in, out := &in.DataClassificationCeiling, &out.DataClassificationCeiling
		*out = new(sharedv1alpha1.Classification)
		**out = **in
	}
	if in.RiskScore != nil {
		in, out := &in.RiskScore, &out.RiskScore
		*out = new(ConditionRiskScore)
		(*in).DeepCopyInto(*out)
	}
	if in.Require != nil {
		in, out := &in.Require, &out.Require
		*out = new(ConditionRequire)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionItem.
func (in *ConditionItem) DeepCopy() *ConditionItem {
	if in == nil {
		return nil
	}
	out := new(ConditionItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionLocation) DeepCopyInto(out *ConditionLocation) {
	*out = *in
	if in.Countries != nil {
		in, out := &in.Countries, &out.Countries
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Regions != nil {
		in, out := &in.Regions, &out.Regions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IPAllowList != nil {
		in, out := &in.IPAllowList, &out.IPAllowList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IPDenyList != nil {
		in, out := &in.IPDenyList, &out.IPDenyList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionLocation.
func (in *ConditionLocation) DeepCopy() *ConditionLocation {
	if in == nil {
		return nil
	}
	out := new(ConditionLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionRequire) DeepCopyInto(out *ConditionRequire) {
	*out = *in
	if in.MFA != nil {
		in, out := &in.MFA, &out.MFA
		*out = new(bool)
		**out = **in
	}
	if in.DeviceCompliant != nil {
		in, out := &in.DeviceCompliant, &out.DeviceCompliant
		*out = new(bool)
		**out = **in
	}
	if in.SSO != nil {
		in, out := &in.SSO, &out.SSO
		*out = new(bool)
		**out = **in
	}
	if in.StepUpAuth != nil {
		in, out := &in.StepUpAuth, &out.StepUpAuth
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionRequire.
func (in *ConditionRequire) DeepCopy() *ConditionRequire {
	if in == nil {
		return nil
	}
	out := new(ConditionRequire)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionRiskScore) DeepCopyInto(out *ConditionRiskScore) {
	*out = *in
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(float64)
		**out = **in
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionRiskScore.
func (in *ConditionRiskScore) DeepCopy() *ConditionRiskScore {
	if in == nil {
		return nil
	}
	out := new(ConditionRiskScore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionSet) DeepCopyInto(out *ConditionSet) {
	*out = *in
	if in.AllOf != nil {
		in, out := &in.AllOf, &out.AllOf
		*out = make([]ConditionItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AnyOf != nil {
		in, out := &in.AnyOf, &out.AnyOf
		*out = make([]ConditionItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NoneOf != nil {
		in, out := &in.NoneOf, &out.NoneOf
		*out = make([]ConditionItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionSet.
func (in *ConditionSet) DeepCopy() *ConditionSet {
	if in == nil {
		return nil
	}
	out := new(ConditionSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionTimeWindow) DeepCopyInto(out *ConditionTimeWindow) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionTimeWindow.
func (in *ConditionTimeWindow) DeepCopy() *ConditionTimeWindow {
	if in == nil {
		return nil
	}
	out := new(ConditionTimeWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConstraintBudget) DeepCopyInto(out *ConstraintBudget) {
	*out = *in
	if in.TokensPerUserPerDay != nil {
		in, out := &in.TokensPerUserPerDay, &out.TokensPerUserPerDay
		*out = new(int64)
		**out = **in
	}
	if in.TokensPerUserPerMonth != nil {
		in, out := &in.TokensPerUserPerMonth, &out.TokensPerUserPerMonth
		*out = new(int64)
		**out = **in
	}
	if in.UsdPerUserPerMonth != nil {
		in, out := &in.UsdPerUserPerMonth, &out.UsdPerUserPerMonth
		*out = new(sharedv1alpha1.MoneyAmount)
		**out = **in
	}
	if in.TokensPerRequest != nil {
		in, out := &in.TokensPerRequest, &out.TokensPerRequest
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConstraintBudget.
func (in *ConstraintBudget) DeepCopy() *ConstraintBudget {
	if in == nil {
		return nil
	}
	out := new(ConstraintBudget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConstraintRateLimit) DeepCopyInto(out *ConstraintRateLimit) {
	*out = *in
	if in.RequestsPerMinute != nil {
		in, out := &in.RequestsPerMinute, &out.RequestsPerMinute
		*out = new(int32)
		**out = **in
	}
	if in.RequestsPerHour != nil {
		in, out := &in.RequestsPerHour, &out.RequestsPerHour
		*out = new(int32)
		**out = **in
	}
	if in.ConcurrentSessions != nil {
		in, out := &in.ConcurrentSessions, &out.ConcurrentSessions
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConstraintRateLimit.
func (in *ConstraintRateLimit) DeepCopy() *ConstraintRateLimit {
	if in == nil {
		return nil
	}
	out := new(ConstraintRateLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObligationAudit) DeepCopyInto(out *ObligationAudit) {
	*out = *in
	if in.IncludePromptHashes != nil {
		in, out := &in.IncludePromptHashes, &out.IncludePromptHashes
		*out = new(bool)
		**out = **in
	}
	if in.ForwardTo != nil {
		in, out := &in.ForwardTo, &out.ForwardTo
		*out = make([]sharedv1alpha1.ResourceRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObligationAudit.
func (in *ObligationAudit) DeepCopy() *ObligationAudit {
	if in == nil {
		return nil
	}
	out := new(ObligationAudit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObligationNotify) DeepCopyInto(out *ObligationNotify) {
	*out = *in
	if in.OnMatch != nil {
		in, out := &in.OnMatch, &out.OnMatch
		*out = make([]ObligationNotifyMatch, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObligationNotify.
func (in *ObligationNotify) DeepCopy() *ObligationNotify {
	if in == nil {
		return nil
	}
	out := new(ObligationNotify)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObligationNotifyMatch) DeepCopyInto(out *ObligationNotifyMatch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObligationNotifyMatch.
func (in *ObligationNotifyMatch) DeepCopy() *ObligationNotifyMatch {
	if in == nil {
		return nil
	}
	out := new(ObligationNotifyMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObligationRedact) DeepCopyInto(out *ObligationRedact) {
	*out = *in
	if in.PatternsRef != nil {
		in, out := &in.PatternsRef, &out.PatternsRef
		*out = new(sharedv1alpha1.ResourceRef)
		**out = **in
	}
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObligationRedact.
func (in *ObligationRedact) DeepCopy() *ObligationRedact {
	if in == nil {
		return nil
	}
	out := new(ObligationRedact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObligationWatermark) DeepCopyInto(out *ObligationWatermark) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObligationWatermark.
func (in *ObligationWatermark) DeepCopy() *ObligationWatermark {
	if in == nil {
		return nil
	}
	out := new(ObligationWatermark)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Policy) DeepCopyInto(out *Policy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Policy.
func (in *Policy) DeepCopy() *Policy {
	if in == nil {
		return nil
	}
	out := new(Policy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Policy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyAction) DeepCopyInto(out *PolicyAction) {
	*out = *in
	if in.Verbs != nil {
		in, out := &in.Verbs, &out.Verbs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyAction.
func (in *PolicyAction) DeepCopy() *PolicyAction {
	if in == nil {
		return nil
	}
	out := new(PolicyAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyActionResources) DeepCopyInto(out *PolicyActionResources) {
	*out = *in
	if in.AnyOf != nil {
		in, out := &in.AnyOf, &out.AnyOf
		*out = make([]ResourceSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyActionResources.
func (in *PolicyActionResources) DeepCopy() *PolicyActionResources {
	if in == nil {
		return nil
	}
	out := new(PolicyActionResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyConflict) DeepCopyInto(out *PolicyConflict) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyConflict.
func (in *PolicyConflict) DeepCopy() *PolicyConflict {
	if in == nil {
		return nil
	}
	out := new(PolicyConflict)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyConstraints) DeepCopyInto(out *PolicyConstraints) {
	*out = *in
	if in.Budget != nil {
		in, out := &in.Budget, &out.Budget
		*out = new(ConstraintBudget)
		(*in).DeepCopyInto(*out)
	}
	if in.RateLimit != nil {
		in, out := &in.RateLimit, &out.RateLimit
		*out = new(ConstraintRateLimit)
		(*in).DeepCopyInto(*out)
	}
	if in.Quota != nil {
		in, out := &in.Quota, &out.Quota
		*out = new(sharedv1alpha1.ResourceRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyConstraints.
func (in *PolicyConstraints) DeepCopy() *PolicyConstraints {
	if in == nil {
		return nil
	}
	out := new(PolicyConstraints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyDecisions24h) DeepCopyInto(out *PolicyDecisions24h) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyDecisions24h.
func (in *PolicyDecisions24h) DeepCopy() *PolicyDecisions24h {
	if in == nil {
		return nil
	}
	out := new(PolicyDecisions24h)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyDistributionStatus) DeepCopyInto(out *PolicyDistributionStatus) {
	*out = *in
	if in.AckedAt != nil {
		in, out := &in.AckedAt, &out.AckedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyDistributionStatus.
func (in *PolicyDistributionStatus) DeepCopy() *PolicyDistributionStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyDistributionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyEffectiveWindow) DeepCopyInto(out *PolicyEffectiveWindow) {
	*out = *in
	if in.NotBefore != nil {
		in, out := &in.NotBefore, &out.NotBefore
		*out = (*in).DeepCopy()
	}
	if in.NotAfter != nil {
		in, out := &in.NotAfter, &out.NotAfter
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyEffectiveWindow.
func (in *PolicyEffectiveWindow) DeepCopy() *PolicyEffectiveWindow {
	if in == nil {
		return nil
	}
	out := new(PolicyEffectiveWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyList) DeepCopyInto(out *PolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Policy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyList.
func (in *PolicyList) DeepCopy() *PolicyList {
	if in == nil {
		return nil
	}
	out := new(PolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyObligations) DeepCopyInto(out *PolicyObligations) {
	*out = *in
	if in.Audit != nil {
		in, out := &in.Audit, &out.Audit
		*out = new(ObligationAudit)
		(*in).DeepCopyInto(*out)
	}
	if in.Redact != nil {
		in, out := &in.Redact, &out.Redact
		*out = new(ObligationRedact)
		(*in).DeepCopyInto(*out)
	}
	if in.Notify != nil {
		in, out := &in.Notify, &out.Notify
		*out = new(ObligationNotify)
		(*in).DeepCopyInto(*out)
	}
	if in.Watermark != nil {
		in, out := &in.Watermark, &out.Watermark
		*out = new(ObligationWatermark)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyObligations.
func (in *PolicyObligations) DeepCopy() *PolicyObligations {
	if in == nil {
		return nil
	}
	out := new(PolicyObligations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicySpec) DeepCopyInto(out *PolicySpec) {
	*out = *in
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int32)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EffectiveWindow != nil {
		in, out := &in.EffectiveWindow, &out.EffectiveWindow
		*out = new(PolicyEffectiveWindow)
		(*in).DeepCopyInto(*out)
	}
	in.Subject.DeepCopyInto(&out.Subject)
	in.Action.DeepCopyInto(&out.Action)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = new(ConditionSet)
		(*in).DeepCopyInto(*out)
	}
	if in.Constraints != nil {
		in, out := &in.Constraints, &out.Constraints
		*out = new(PolicyConstraints)
		(*in).DeepCopyInto(*out)
	}
	if in.Approvals != nil {
		in, out := &in.Approvals, &out.Approvals
		*out = make([]ApprovalSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Obligations != nil {
		in, out := &in.Obligations, &out.Obligations
		*out = new(PolicyObligations)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicySpec.
func (in *PolicySpec) DeepCopy() *PolicySpec {
	if in == nil {
		return nil
	}
	out := new(PolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyStatus) DeepCopyInto(out *PolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BundleVersion != nil {
		in, out := &in.BundleVersion, &out.BundleVersion
		*out = new(int64)
		**out = **in
	}
	if in.Distribution != nil {
		in, out := &in.Distribution, &out.Distribution
		*out = make([]PolicyDistributionStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Decisions24h != nil {
		in, out := &in.Decisions24h, &out.Decisions24h
		*out = new(PolicyDecisions24h)
		**out = **in
	}
	if in.Conflicts != nil {
		in, out := &in.Conflicts, &out.Conflicts
		*out = make([]PolicyConflict, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyStatus.
func (in *PolicyStatus) DeepCopy() *PolicyStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Quota) DeepCopyInto(out *Quota) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Quota.
func (in *Quota) DeepCopy() *Quota {
	if in == nil {
		return nil
	}
	out := new(Quota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Quota) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaList) DeepCopyInto(out *QuotaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Quota, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaList.
func (in *QuotaList) DeepCopy() *QuotaList {
	if in == nil {
		return nil
	}
	out := new(QuotaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QuotaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaScope) DeepCopyInto(out *QuotaScope) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaScope.
func (in *QuotaScope) DeepCopy() *QuotaScope {
	if in == nil {
		return nil
	}
	out := new(QuotaScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaSpec) DeepCopyInto(out *QuotaSpec) {
	*out = *in
	out.Scope = in.Scope
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = make(map[string]intstr.IntOrString, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaSpec.
func (in *QuotaSpec) DeepCopy() *QuotaSpec {
	if in == nil {
		return nil
	}
	out := new(QuotaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaStatus) DeepCopyInto(out *QuotaStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Used != nil {
		in, out := &in.Used, &out.Used
		*out = make(map[string]intstr.IntOrString, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaStatus.
func (in *QuotaStatus) DeepCopy() *QuotaStatus {
	if in == nil {
		return nil
	}
	out := new(QuotaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceMatch) DeepCopyInto(out *ResourceMatch) {
	*out = *in
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(sharedv1alpha1.ResourceRef)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceMatch.
func (in *ResourceMatch) DeepCopy() *ResourceMatch {
	if in == nil {
		return nil
	}
	out := new(ResourceMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSelector) DeepCopyInto(out *ResourceSelector) {
	*out = *in
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = new(ResourceMatch)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSelector.
func (in *ResourceSelector) DeepCopy() *ResourceSelector {
	if in == nil {
		return nil
	}
	out := new(ResourceSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubjectEntry) DeepCopyInto(out *SubjectEntry) {
	*out = *in
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = new(SubjectMatch)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubjectEntry.
func (in *SubjectEntry) DeepCopy() *SubjectEntry {
	if in == nil {
		return nil
	}
	out := new(SubjectEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubjectMatch) DeepCopyInto(out *SubjectMatch) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubjectMatch.
func (in *SubjectMatch) DeepCopy() *SubjectMatch {
	if in == nil {
		return nil
	}
	out := new(SubjectMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubjectSelector) DeepCopyInto(out *SubjectSelector) {
	*out = *in
	if in.AnyOf != nil {
		in, out := &in.AnyOf, &out.AnyOf
		*out = make([]SubjectEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubjectSelector.
func (in *SubjectSelector) DeepCopy() *SubjectSelector {
	if in == nil {
		return nil
	}
	out := new(SubjectSelector)
	in.DeepCopyInto(out)
	return out
}
