apiVersion: core.ai-keeper.io/v1alpha1
kind: ServiceAccount
metadata:
  name: healthcare-sa
  namespace: healthcare-dept
spec:
  displayName: Healthcare Pack Service Account
  allowOnBehalfOf: true
  tokenLifetime: 15m
  audiences:
    - aik-gateway
    - ehr-api
    - pharmacy-system
