//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	sharedv1alpha1 "github.com/ai-keeper/ai-keeper/api/shared/v1alpha1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditAction) DeepCopyInto(out *AuditAction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditAction.
func (in *AuditAction) DeepCopy() *AuditAction {
	if in == nil {
		return nil
	}
	out := new(AuditAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditCitation) DeepCopyInto(out *AuditCitation) {
	*out = *in
	if in.Score != nil {
		in, out := &in.Score, &out.Score
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditCitation.
func (in *AuditCitation) DeepCopy() *AuditCitation {
	if in == nil {
		return nil
	}
	out := new(AuditCitation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditCompliance) DeepCopyInto(out *AuditCompliance) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Reviewed != nil {
		in, out := &in.Reviewed, &out.Reviewed
		*out = new(bool)
		**out = **in
	}
	if in.ReviewedAt != nil {
		in, out := &in.ReviewedAt, &out.ReviewedAt
		*out = (*in).DeepCopy()
	}
	if in.Holds != nil {
		in, out := &in.Holds, &out.Holds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditCompliance.
func (in *AuditCompliance) DeepCopy() *AuditCompliance {
	if in == nil {
		return nil
	}
	out := new(AuditCompliance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditCost) DeepCopyInto(out *AuditCost) {
	*out = *in
	if in.Tokens != nil {
		in, out := &in.Tokens, &out.Tokens
		*out = new(AuditCostTokens)
		**out = **in
	}
	if in.Usd != nil {
		in, out := &in.Usd, &out.Usd
		*out = new(sharedv1alpha1.MoneyAmount)
		**out = **in
	}
	if in.DurationMs != nil {
		in, out := &in.DurationMs, &out.DurationMs
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditCost.
func (in *AuditCost) DeepCopy() *AuditCost {
	if in == nil {
		return nil
	}
	out := new(AuditCost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditCostTokens) DeepCopyInto(out *AuditCostTokens) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditCostTokens.
func (in *AuditCostTokens) DeepCopy() *AuditCostTokens {
	if in == nil {
		return nil
	}
	out := new(AuditCostTokens)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditEvent) DeepCopyInto(out *AuditEvent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditEvent.
func (in *AuditEvent) DeepCopy() *AuditEvent {
	if in == nil {
		return nil
	}
	out := new(AuditEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuditEvent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditEventList) DeepCopyInto(out *AuditEventList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AuditEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditEventList.
func (in *AuditEventList) DeepCopy() *AuditEventList {
	if in == nil {
		return nil
	}
	out := new(AuditEventList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuditEventList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditEventSpec) DeepCopyInto(out *AuditEventSpec) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
	if in.Trace != nil {
		in, out := &in.Trace, &out.Trace
		*out = new(AuditEventTrace)
		**out = **in
	}
	in.Principal.DeepCopyInto(&out.Principal)
	out.Action = in.Action
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(AuditPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Request != nil {
		in, out := &in.Request, &out.Request
		*out = new(AuditRequest)
		(*in).DeepCopyInto(*out)
	}
	if in.Response != nil {
		in, out := &in.Response, &out.Response
		*out = new(AuditResponse)
		(*in).DeepCopyInto(*out)
	}
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]AuditStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Cost != nil {
		in, out := &in.Cost, &out.Cost
		*out = new(AuditCost)
		(*in).DeepCopyInto(*out)
	}
	if in.Guardrails != nil {
		in, out := &in.Guardrails, &out.Guardrails
		*out = new(AuditGuardrails)
		(*in).DeepCopyInto(*out)
	}
	if in.Compliance != nil {
		in, out := &in.Compliance, &out.Compliance
		*out = new(AuditCompliance)
		(*in).DeepCopyInto(*out)
	}
	if in.Outcome != nil {
		in, out := &in.Outcome, &out.Outcome
		*out = new(AuditOutcome)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditEventSpec.
func (in *AuditEventSpec) DeepCopy() *AuditEventSpec {
	if in == nil {
		return nil
	}
	out := new(AuditEventSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditEventStatus) DeepCopyInto(out *AuditEventStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditEventStatus.
func (in *AuditEventStatus) DeepCopy() *AuditEventStatus {
	if in == nil {
		return nil
	}
	out := new(AuditEventStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditEventTrace) DeepCopyInto(out *AuditEventTrace) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditEventTrace.
func (in *AuditEventTrace) DeepCopy() *AuditEventTrace {
	if in == nil {
		return nil
	}
	out := new(AuditEventTrace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditGuardrailHit) DeepCopyInto(out *AuditGuardrailHit) {
	*out = *in
	if in.Score != nil {
		in, out := &in.Score, &out.Score
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditGuardrailHit.
func (in *AuditGuardrailHit) DeepCopy() *AuditGuardrailHit {
	if in == nil {
		return nil
	}
	out := new(AuditGuardrailHit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditGuardrails) DeepCopyInto(out *AuditGuardrails) {
	*out = *in
	if in.Triggered != nil {
		in, out := &in.Triggered, &out.Triggered
		*out = make([]AuditGuardrailHit, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Blocked != nil {
		in, out := &in.Blocked, &out.Blocked
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditGuardrails.
func (in *AuditGuardrails) DeepCopy() *AuditGuardrails {
	if in == nil {
		return nil
	}
	out := new(AuditGuardrails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditOutcome) DeepCopyInto(out *AuditOutcome) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditOutcome.
func (in *AuditOutcome) DeepCopy() *AuditOutcome {
	if in == nil {
		return nil
	}
	out := new(AuditOutcome)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditPolicy) DeepCopyInto(out *AuditPolicy) {
	*out = *in
	if in.MatchedPolicies != nil {
		in, out := &in.MatchedPolicies, &out.MatchedPolicies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ObligationsApplied != nil {
		in, out := &in.ObligationsApplied, &out.ObligationsApplied
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditPolicy.
func (in *AuditPolicy) DeepCopy() *AuditPolicy {
	if in == nil {
		return nil
	}
	out := new(AuditPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditPrincipal) DeepCopyInto(out *AuditPrincipal) {
	*out = *in
	if in.User != nil {
		in, out := &in.User, &out.User
		*out = new(AuditPrincipalUser)
		(*in).DeepCopyInto(*out)
	}
	out.Agent = in.Agent
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(AuditPrincipalSA)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditPrincipal.
func (in *AuditPrincipal) DeepCopy() *AuditPrincipal {
	if in == nil {
		return nil
	}
	out := new(AuditPrincipal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditPrincipalAgent) DeepCopyInto(out *AuditPrincipalAgent) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditPrincipalAgent.
func (in *AuditPrincipalAgent) DeepCopy() *AuditPrincipalAgent {
	if in == nil {
		return nil
	}
	out := new(AuditPrincipalAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditPrincipalSA) DeepCopyInto(out *AuditPrincipalSA) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditPrincipalSA.
func (in *AuditPrincipalSA) DeepCopy() *AuditPrincipalSA {
	if in == nil {
		return nil
	}
	out := new(AuditPrincipalSA)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditPrincipalUser) DeepCopyInto(out *AuditPrincipalUser) {
	*out = *in
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditPrincipalUser.
func (in *AuditPrincipalUser) DeepCopy() *AuditPrincipalUser {
	if in == nil {
		return nil
	}
	out := new(AuditPrincipalUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditRequest) DeepCopyInto(out *AuditRequest) {
	*out = *in
	if in.InputRef != nil {
		in, out := &in.InputRef, &out.InputRef
		*out = new(sharedv1alpha1.ResourceRef)
		**out = **in
	}
	if in.Classification != nil {
		in, out := &in.Classification, &out.Classification
		*out = new(sharedv1alpha1.Classification)
		**out = **in
	}
	if in.Redactions != nil {
		in, out := &in.Redactions, &out.Redactions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SizeBytes != nil {
		in, out := &in.SizeBytes, &out.SizeBytes
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditRequest.
func (in *AuditRequest) DeepCopy() *AuditRequest {
	if in == nil {
		return nil
	}
	out := new(AuditRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditResponse) DeepCopyInto(out *AuditResponse) {
	*out = *in
	if in.OutputRef != nil {
		in, out := &in.OutputRef, &out.OutputRef
		*out = new(sharedv1alpha1.ResourceRef)
		**out = **in
	}
	if in.Confidence != nil {
		in, out := &in.Confidence, &out.Confidence
		*out = new(float64)
		**out = **in
	}
	if in.Citations != nil {
		in, out := &in.Citations, &out.Citations
		*out = make([]AuditCitation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Classification != nil {
		in, out := &in.Classification, &out.Classification
		*out = new(sharedv1alpha1.Classification)
		**out = **in
	}
	if in.SizeBytes != nil {
		in, out := &in.SizeBytes, &out.SizeBytes
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditResponse.
func (in *AuditResponse) DeepCopy() *AuditResponse {
	if in == nil {
		return nil
	}
	out := new(AuditResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditStep) DeepCopyInto(out *AuditStep) {
	*out = *in
	if in.Index != nil {
		in, out := &in.Index, &out.Index
		*out = new(int32)
		**out = **in
	}
	if in.Tool != nil {
		in, out := &in.Tool, &out.Tool
		*out = new(sharedv1alpha1.ResourceRef)
		**out = **in
	}
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(sharedv1alpha1.ResourceRef)
		**out = **in
	}
	if in.TokensIn != nil {
		in, out := &in.TokensIn, &out.TokensIn
		*out = new(int64)
		**out = **in
	}
	if in.TokensOut != nil {
		in, out := &in.TokensOut, &out.TokensOut
		*out = new(int64)
		**out = **in
	}
	if in.LatencyMs != nil {
		in, out := &in.LatencyMs, &out.LatencyMs
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditStep.
func (in *AuditStep) DeepCopy() *AuditStep {
	if in == nil {
		return nil
	}
	out := new(AuditStep)
	in.DeepCopyInto(out)
	return out
}
