// Copyright 2026 The AIP Authors.
//
// Audit Sink gRPC contract.
// Implements design.md §7.11 / §8.1 / §10.2 and Requirements B12, F4, F5,
// F22 (audit completeness, immutability, eventHash).
//
// This is the canonical wire format for AuditEvent. The Audit Sink dual-
// writes to ClickHouse (real-time query) and S3 + Object Lock (WORM, 7-year
// retention). `event_hash` MUST equal sha256(canonical(spec)) per RFC 8785
// (Property 10).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: aip/v1/audit.proto

package aipv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuditSinkService_Emit_FullMethodName  = "/aip.v1.AuditSinkService/Emit"
	AuditSinkService_Query_FullMethodName = "/aip.v1.AuditSinkService/Query"
)

// AuditSinkServiceClient is the client API for AuditSinkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuditSinkServiceClient interface {
	// Emit one AuditEvent. Producer-side at-least-once; Sink-side dedup by
	// (invocation_id, step_id) (B12 / F22).
	Emit(ctx context.Context, in *EmitRequest, opts ...grpc.CallOption) (*EmitResponse, error)
	// Server-streamed query. Read-only (Property 9 — immutability).
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AuditEvent], error)
}

type auditSinkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuditSinkServiceClient(cc grpc.ClientConnInterface) AuditSinkServiceClient {
	return &auditSinkServiceClient{cc}
}

func (c *auditSinkServiceClient) Emit(ctx context.Context, in *EmitRequest, opts ...grpc.CallOption) (*EmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmitResponse)
	err := c.cc.Invoke(ctx, AuditSinkService_Emit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditSinkServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AuditEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AuditSinkService_ServiceDesc.Streams[0], AuditSinkService_Query_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[QueryRequest, AuditEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AuditSinkService_QueryClient = grpc.ServerStreamingClient[AuditEvent]

// AuditSinkServiceServer is the server API for AuditSinkService service.
// All implementations should embed UnimplementedAuditSinkServiceServer
// for forward compatibility.
type AuditSinkServiceServer interface {
	// Emit one AuditEvent. Producer-side at-least-once; Sink-side dedup by
	// (invocation_id, step_id) (B12 / F22).
	Emit(context.Context, *EmitRequest) (*EmitResponse, error)
	// Server-streamed query. Read-only (Property 9 — immutability).
	Query(*QueryRequest, grpc.ServerStreamingServer[AuditEvent]) error
}

// UnimplementedAuditSinkServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuditSinkServiceServer struct{}

func (UnimplementedAuditSinkServiceServer) Emit(context.Context, *EmitRequest) (*EmitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Emit not implemented")
}
func (UnimplementedAuditSinkServiceServer) Query(*QueryRequest, grpc.ServerStreamingServer[AuditEvent]) error {
	return status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedAuditSinkServiceServer) testEmbeddedByValue() {}

// UnsafeAuditSinkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuditSinkServiceServer will
// result in compilation errors.
type UnsafeAuditSinkServiceServer interface {
	mustEmbedUnimplementedAuditSinkServiceServer()
}

func RegisterAuditSinkServiceServer(s grpc.ServiceRegistrar, srv AuditSinkServiceServer) {
	// If the following call pancis, it indicates UnimplementedAuditSinkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuditSinkService_ServiceDesc, srv)
}

func _AuditSinkService_Emit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditSinkServiceServer).Emit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditSinkService_Emit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditSinkServiceServer).Emit(ctx, req.(*EmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditSinkService_Query_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AuditSinkServiceServer).Query(m, &grpc.GenericServerStream[QueryRequest, AuditEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AuditSinkService_QueryServer = grpc.ServerStreamingServer[AuditEvent]

// AuditSinkService_ServiceDesc is the grpc.ServiceDesc for AuditSinkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuditSinkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aip.v1.AuditSinkService",
	HandlerType: (*AuditSinkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Emit",
			Handler:    _AuditSinkService_Emit_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Query",
			Handler:       _AuditSinkService_Query_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "aip/v1/audit.proto",
}
