// Copyright 2026 The AIP Authors.
//
// Cost Tracker gRPC contract.
// Implements design.md §7.12 and Requirements A8 (Budget controller),
// B11 (cost computation), Property 31 (cost calc purity).
//
// `Compute()` is a pure function over (usage, pricing) and is safe to call
// in-process from PEP / Agent Runtime; the gRPC surface exists so that
// Python / TS callers and the Budget Enforcer sidecar can share a single
// implementation.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: aip/v1/cost.proto

package aipv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CostService_Compute_FullMethodName = "/aip.v1.CostService/Compute"
	CostService_Record_FullMethodName  = "/aip.v1.CostService/Record"
	CostService_Balance_FullMethodName = "/aip.v1.CostService/Balance"
)

// CostServiceClient is the client API for CostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CostServiceClient interface {
	// Pure cost calculation (Property 31 — same input ⇒ same output, ≥ 0).
	Compute(ctx context.Context, in *ComputeRequest, opts ...grpc.CallOption) (*ComputeResponse, error)
	// Persist usage + debit Redis budget counters (B11 / A8).
	Record(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*RecordResponse, error)
	// Read current balance for one or more scopes (Console / aikctl).
	Balance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error)
}

type costServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCostServiceClient(cc grpc.ClientConnInterface) CostServiceClient {
	return &costServiceClient{cc}
}

func (c *costServiceClient) Compute(ctx context.Context, in *ComputeRequest, opts ...grpc.CallOption) (*ComputeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComputeResponse)
	err := c.cc.Invoke(ctx, CostService_Compute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *costServiceClient) Record(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*RecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordResponse)
	err := c.cc.Invoke(ctx, CostService_Record_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *costServiceClient) Balance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BalanceResponse)
	err := c.cc.Invoke(ctx, CostService_Balance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CostServiceServer is the server API for CostService service.
// All implementations should embed UnimplementedCostServiceServer
// for forward compatibility.
type CostServiceServer interface {
	// Pure cost calculation (Property 31 — same input ⇒ same output, ≥ 0).
	Compute(context.Context, *ComputeRequest) (*ComputeResponse, error)
	// Persist usage + debit Redis budget counters (B11 / A8).
	Record(context.Context, *RecordRequest) (*RecordResponse, error)
	// Read current balance for one or more scopes (Console / aikctl).
	Balance(context.Context, *BalanceRequest) (*BalanceResponse, error)
}

// UnimplementedCostServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCostServiceServer struct{}

func (UnimplementedCostServiceServer) Compute(context.Context, *ComputeRequest) (*ComputeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Compute not implemented")
}
func (UnimplementedCostServiceServer) Record(context.Context, *RecordRequest) (*RecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Record not implemented")
}
func (UnimplementedCostServiceServer) Balance(context.Context, *BalanceRequest) (*BalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Balance not implemented")
}
func (UnimplementedCostServiceServer) testEmbeddedByValue() {}

// UnsafeCostServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CostServiceServer will
// result in compilation errors.
type UnsafeCostServiceServer interface {
	mustEmbedUnimplementedCostServiceServer()
}

func RegisterCostServiceServer(s grpc.ServiceRegistrar, srv CostServiceServer) {
	// If the following call pancis, it indicates UnimplementedCostServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CostService_ServiceDesc, srv)
}

func _CostService_Compute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CostServiceServer).Compute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CostService_Compute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CostServiceServer).Compute(ctx, req.(*ComputeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CostService_Record_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CostServiceServer).Record(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CostService_Record_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CostServiceServer).Record(ctx, req.(*RecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CostService_Balance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CostServiceServer).Balance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CostService_Balance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CostServiceServer).Balance(ctx, req.(*BalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CostService_ServiceDesc is the grpc.ServiceDesc for CostService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CostService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aip.v1.CostService",
	HandlerType: (*CostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Compute",
			Handler:    _CostService_Compute_Handler,
		},
		{
			MethodName: "Record",
			Handler:    _CostService_Record_Handler,
		},
		{
			MethodName: "Balance",
			Handler:    _CostService_Balance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aip/v1/cost.proto",
}
