// Copyright 2026 The AIP Authors.
//
// DLP / Classification Engine gRPC contract.
// Implements design.md §4.2 / §10.2 and Requirement B4.
//
// Inspect() detects PII / sensitive data in inbound and outbound text,
// returning either masked text (mode=mask), a block verdict, or pass-through
// classification metadata.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: aip/v1/dlp.proto

package aipv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DlpService_Inspect_FullMethodName = "/aip.v1.DlpService/Inspect"
)

// DlpServiceClient is the client API for DlpService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DlpServiceClient interface {
	// Inspect a single text payload (B4.1 / B4.2 / B4.3).
	Inspect(ctx context.Context, in *InspectRequest, opts ...grpc.CallOption) (*InspectResponse, error)
}

type dlpServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDlpServiceClient(cc grpc.ClientConnInterface) DlpServiceClient {
	return &dlpServiceClient{cc}
}

func (c *dlpServiceClient) Inspect(ctx context.Context, in *InspectRequest, opts ...grpc.CallOption) (*InspectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectResponse)
	err := c.cc.Invoke(ctx, DlpService_Inspect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DlpServiceServer is the server API for DlpService service.
// All implementations should embed UnimplementedDlpServiceServer
// for forward compatibility.
type DlpServiceServer interface {
	// Inspect a single text payload (B4.1 / B4.2 / B4.3).
	Inspect(context.Context, *InspectRequest) (*InspectResponse, error)
}

// UnimplementedDlpServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDlpServiceServer struct{}

func (UnimplementedDlpServiceServer) Inspect(context.Context, *InspectRequest) (*InspectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Inspect not implemented")
}
func (UnimplementedDlpServiceServer) testEmbeddedByValue() {}

// UnsafeDlpServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DlpServiceServer will
// result in compilation errors.
type UnsafeDlpServiceServer interface {
	mustEmbedUnimplementedDlpServiceServer()
}

func RegisterDlpServiceServer(s grpc.ServiceRegistrar, srv DlpServiceServer) {
	// If the following call pancis, it indicates UnimplementedDlpServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DlpService_ServiceDesc, srv)
}

func _DlpService_Inspect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DlpServiceServer).Inspect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DlpService_Inspect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DlpServiceServer).Inspect(ctx, req.(*InspectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DlpService_ServiceDesc is the grpc.ServiceDesc for DlpService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DlpService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aip.v1.DlpService",
	HandlerType: (*DlpServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Inspect",
			Handler:    _DlpService_Inspect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aip/v1/dlp.proto",
}
