// Copyright 2026 The AIP Authors.
//
// PEP ↔ PDP gRPC contract.
// Implements design.md §4.2 / §10.2 and Requirements B2.
//
// The PEP (Policy Enforcement Point) calls Decide() once per inbound AI
// invocation; the PDP returns a decision plus an obligation list that the PEP
// must execute (audit / redact / watermark / notify / require_approval).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: aip/v1/pdp.proto

package aipv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PolicyDecisionService_Decide_FullMethodName = "/aip.v1.PolicyDecisionService/Decide"
	PolicyDecisionService_Watch_FullMethodName  = "/aip.v1.PolicyDecisionService/Watch"
)

// PolicyDecisionServiceClient is the client API for PolicyDecisionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PolicyDecisionServiceClient interface {
	// Decide a single inbound action. PEP MUST fail-closed if this RPC times
	// out within the 1s SLA (Requirement B2.8 / F6).
	Decide(ctx context.Context, in *DecisionRequest, opts ...grpc.CallOption) (*DecisionResponse, error)
	// Stream new bundle versions to PDP replicas (Requirement A5.5/A5.6).
	Watch(ctx context.Context, in *BundleSubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BundleEvent], error)
}

type policyDecisionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicyDecisionServiceClient(cc grpc.ClientConnInterface) PolicyDecisionServiceClient {
	return &policyDecisionServiceClient{cc}
}

func (c *policyDecisionServiceClient) Decide(ctx context.Context, in *DecisionRequest, opts ...grpc.CallOption) (*DecisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecisionResponse)
	err := c.cc.Invoke(ctx, PolicyDecisionService_Decide_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyDecisionServiceClient) Watch(ctx context.Context, in *BundleSubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BundleEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PolicyDecisionService_ServiceDesc.Streams[0], PolicyDecisionService_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BundleSubscribeRequest, BundleEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PolicyDecisionService_WatchClient = grpc.ServerStreamingClient[BundleEvent]

// PolicyDecisionServiceServer is the server API for PolicyDecisionService service.
// All implementations should embed UnimplementedPolicyDecisionServiceServer
// for forward compatibility.
type PolicyDecisionServiceServer interface {
	// Decide a single inbound action. PEP MUST fail-closed if this RPC times
	// out within the 1s SLA (Requirement B2.8 / F6).
	Decide(context.Context, *DecisionRequest) (*DecisionResponse, error)
	// Stream new bundle versions to PDP replicas (Requirement A5.5/A5.6).
	Watch(*BundleSubscribeRequest, grpc.ServerStreamingServer[BundleEvent]) error
}

// UnimplementedPolicyDecisionServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPolicyDecisionServiceServer struct{}

func (UnimplementedPolicyDecisionServiceServer) Decide(context.Context, *DecisionRequest) (*DecisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Decide not implemented")
}
func (UnimplementedPolicyDecisionServiceServer) Watch(*BundleSubscribeRequest, grpc.ServerStreamingServer[BundleEvent]) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedPolicyDecisionServiceServer) testEmbeddedByValue() {}

// UnsafePolicyDecisionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolicyDecisionServiceServer will
// result in compilation errors.
type UnsafePolicyDecisionServiceServer interface {
	mustEmbedUnimplementedPolicyDecisionServiceServer()
}

func RegisterPolicyDecisionServiceServer(s grpc.ServiceRegistrar, srv PolicyDecisionServiceServer) {
	// If the following call pancis, it indicates UnimplementedPolicyDecisionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PolicyDecisionService_ServiceDesc, srv)
}

func _PolicyDecisionService_Decide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyDecisionServiceServer).Decide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyDecisionService_Decide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyDecisionServiceServer).Decide(ctx, req.(*DecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyDecisionService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BundleSubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PolicyDecisionServiceServer).Watch(m, &grpc.GenericServerStream[BundleSubscribeRequest, BundleEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PolicyDecisionService_WatchServer = grpc.ServerStreamingServer[BundleEvent]

// PolicyDecisionService_ServiceDesc is the grpc.ServiceDesc for PolicyDecisionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PolicyDecisionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aip.v1.PolicyDecisionService",
	HandlerType: (*PolicyDecisionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Decide",
			Handler:    _PolicyDecisionService_Decide_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _PolicyDecisionService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "aip/v1/pdp.proto",
}
