// Copyright 2026 The AIP Authors.
//
// Model Router gRPC contract.
// Implements design.md §4.2 / §10.2 and Requirement B8.
//
// Resolves a logical alias (`reasoner` / `embedder` / `vision`) to a concrete
// ModelEndpoint at request time, applying CEL rules + weighted routing +
// semantic cache + per-endpoint fallback chain.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: aip/v1/router.proto

package aipv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModelRouterService_Route_FullMethodName        = "/aip.v1.ModelRouterService/Route"
	ModelRouterService_CompleteChat_FullMethodName = "/aip.v1.ModelRouterService/CompleteChat"
)

// ModelRouterServiceClient is the client API for ModelRouterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModelRouterServiceClient interface {
	// Resolve a logical alias to a concrete endpoint (B8.1 / B8.2).
	Route(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteResponse, error)
	// Streamed chat completion. Wraps endpoint client + semantic cache +
	// fallback retries (B8.4 / B8.5 / B8.6).
	CompleteChat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatChunk], error)
}

type modelRouterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModelRouterServiceClient(cc grpc.ClientConnInterface) ModelRouterServiceClient {
	return &modelRouterServiceClient{cc}
}

func (c *modelRouterServiceClient) Route(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteResponse)
	err := c.cc.Invoke(ctx, ModelRouterService_Route_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelRouterServiceClient) CompleteChat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ModelRouterService_ServiceDesc.Streams[0], ModelRouterService_CompleteChat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ModelRouterService_CompleteChatClient = grpc.ServerStreamingClient[ChatChunk]

// ModelRouterServiceServer is the server API for ModelRouterService service.
// All implementations should embed UnimplementedModelRouterServiceServer
// for forward compatibility.
type ModelRouterServiceServer interface {
	// Resolve a logical alias to a concrete endpoint (B8.1 / B8.2).
	Route(context.Context, *RouteRequest) (*RouteResponse, error)
	// Streamed chat completion. Wraps endpoint client + semantic cache +
	// fallback retries (B8.4 / B8.5 / B8.6).
	CompleteChat(*ChatRequest, grpc.ServerStreamingServer[ChatChunk]) error
}

// UnimplementedModelRouterServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelRouterServiceServer struct{}

func (UnimplementedModelRouterServiceServer) Route(context.Context, *RouteRequest) (*RouteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Route not implemented")
}
func (UnimplementedModelRouterServiceServer) CompleteChat(*ChatRequest, grpc.ServerStreamingServer[ChatChunk]) error {
	return status.Errorf(codes.Unimplemented, "method CompleteChat not implemented")
}
func (UnimplementedModelRouterServiceServer) testEmbeddedByValue() {}

// UnsafeModelRouterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelRouterServiceServer will
// result in compilation errors.
type UnsafeModelRouterServiceServer interface {
	mustEmbedUnimplementedModelRouterServiceServer()
}

func RegisterModelRouterServiceServer(s grpc.ServiceRegistrar, srv ModelRouterServiceServer) {
	// If the following call pancis, it indicates UnimplementedModelRouterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModelRouterService_ServiceDesc, srv)
}

func _ModelRouterService_Route_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelRouterServiceServer).Route(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelRouterService_Route_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelRouterServiceServer).Route(ctx, req.(*RouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelRouterService_CompleteChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ModelRouterServiceServer).CompleteChat(m, &grpc.GenericServerStream[ChatRequest, ChatChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ModelRouterService_CompleteChatServer = grpc.ServerStreamingServer[ChatChunk]

// ModelRouterService_ServiceDesc is the grpc.ServiceDesc for ModelRouterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelRouterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aip.v1.ModelRouterService",
	HandlerType: (*ModelRouterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Route",
			Handler:    _ModelRouterService_Route_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CompleteChat",
			Handler:       _ModelRouterService_CompleteChat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "aip/v1/router.proto",
}
